/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Product;
import Model.ProductManager;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Personal
 */
public class BuscarProductoPanel extends javax.swing.JPanel {
    private MainFrame parentFrame;
    /**
     * Creates new form SearchDialogg
     */
    public BuscarProductoPanel() {
        initComponents();
        addCategoryListener();
    }
    public BuscarProductoPanel(MainFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        addCategoryListener();
    }

    public void setBuscarProductoParentFrame(MainFrame parentMainFrame) {
        this.parentFrame = parentFrame;
    }

    
    private void addCategoryListener() {
        jComboBox1.addItemListener(evt -> {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                String categoria = (String) evt.getItem();
                actualizarModelosSegunCategoria(categoria);
            }
        });
    }
    private void actualizarModelosSegunCategoria(String categoria) {
        // Ejemplo simple; ajusta según tu catálogo real
        String[] modelos;
        switch (categoria.toLowerCase()) {
            case "monitor" -> modelos = new String[] { "LG", "DELL", "Acer", "Asus" };
            case "accesorios" -> modelos = new String[] { "Redragon", "Razer", "Logitech", "Fury" };
            case "celulares" -> modelos = new String[] { "Samsung", "Xiaomi", "Huawei", "iPhone" };
            case "audio" -> modelos = new String[] { "Astro", "Sony", "Bose", "JBL" };
            case "gaming" -> modelos = new String[] { "AMD", "Intel", "Nvidia" };
            default -> modelos = new String[] { };
        }
        jComboBox2.setModel(new DefaultComboBoxModel<>(modelos));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicioButtonBuscarPanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idNombreTextFieldBuscarPanel = new javax.swing.JTextField();
        buscarButtonBuscarPanel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1366, 768));

        inicioButtonBuscarPanel.setText("Inicio");
        inicioButtonBuscarPanel.setPreferredSize(new java.awt.Dimension(161, 41));
        inicioButtonBuscarPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioButtonBuscarPanelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Buscar producto");
        jLabel1.setPreferredSize(new java.awt.Dimension(465, 87));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("ID o nombre:");
        jLabel2.setPreferredSize(new java.awt.Dimension(243, 55));

        idNombreTextFieldBuscarPanel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        idNombreTextFieldBuscarPanel.setPreferredSize(new java.awt.Dimension(1271, 55));
        idNombreTextFieldBuscarPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNombreTextFieldBuscarPanelActionPerformed(evt);
            }
        });

        buscarButtonBuscarPanel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buscarButtonBuscarPanel.setText("Buscar");
        buscarButtonBuscarPanel.setPreferredSize(new java.awt.Dimension(1203, 105));
        buscarButtonBuscarPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonBuscarPanelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Categoría:");
        jLabel3.setPreferredSize(new java.awt.Dimension(243, 55));

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monitor", "Accesorios", "Celulares", "Audio", "Gaming" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(407, 55));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Modelo:");
        jLabel4.setPreferredSize(new java.awt.Dimension(243, 55));

        jComboBox2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LG", "Xiaomi", "Asus", "DELL", "Iphone", "Samsung", "Huawei", "AMD", "Redragon", "Astro", "Fury", "Razer", "Intel", "Wooting", "Logitech", "Acer" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(407, 55));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(173, 173, 173)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(284, 284, 284))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idNombreTextFieldBuscarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(buscarButtonBuscarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(inicioButtonBuscarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inicioButtonBuscarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(88, 88, 88)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(idNombreTextFieldBuscarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(buscarButtonBuscarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleName("ID o nombre");
    }// </editor-fold>//GEN-END:initComponents

    private void idNombreTextFieldBuscarPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNombreTextFieldBuscarPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNombreTextFieldBuscarPanelActionPerformed

    private void buscarButtonBuscarPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonBuscarPanelActionPerformed
        String texto = idNombreTextFieldBuscarPanel.getText().trim();
        String categoria = (String) jComboBox1.getSelectedItem();
        String modelo = (String) jComboBox2.getSelectedItem();

        // 2) Validar al menos un criterio
        boolean sinTexto = texto.isEmpty();
        boolean sinCategoria = categoria == null || categoria.equals("");
        boolean sinModelo = modelo == null || modelo.equals("");

        if (sinTexto && sinCategoria && sinModelo) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe ingresar al menos un criterio de búsqueda.",
                    "Criterio vacío",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3) Buscar en el catálogo
        List<Product> resultados = ProductManager.buscarProductos(texto, categoria, modelo);

        // 4) Sin resultados
        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se encontraron productos con los criterios ingresados.",
                    "Sin resultados",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // 5) Mostrar resultados en la vista adecuada
        abrirVistaResultados(categoria, resultados);
    }//GEN-LAST:event_buscarButtonBuscarPanelActionPerformed

    private void inicioButtonBuscarPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioButtonBuscarPanelActionPerformed
        if (parentFrame != null) {
            parentFrame.showCard(MainFrame.MENU_CLIENTE_CARD);
        } else {
            System.err.println("Error: No se ha establecido referencia al MainFrame");
        }
    }//GEN-LAST:event_inicioButtonBuscarPanelActionPerformed
    
     private void abrirVistaResultados(String categoria, List<Product> productos) {
        JFrame resultsFrame = new JFrame("¡Productos disponibles! - " + categoria);
        resultsFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        JPanel detallePanel;
        switch (categoria.toLowerCase()) {
            case "accesorios" -> detallePanel = new ProductDetailPanelAccesorios((MainFrame) productos);
            case "celulares"   -> detallePanel = new ProductDetailPanelCelulares((MainFrame) productos);
            case "audio"       -> detallePanel = new ProductDetailPanelAudio((MainFrame) productos);
            case "gaming"      -> detallePanel = new ProductDetailPanelGaming((MainFrame) productos);
            default            -> detallePanel = new ProductDetailPanel((MainFrame) productos); // Monitores / genérico
        }

        resultsFrame.getContentPane().add(detallePanel);
        resultsFrame.pack();
        resultsFrame.setLocationRelativeTo(null);
        resultsFrame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButtonBuscarPanel;
    private javax.swing.JTextField idNombreTextFieldBuscarPanel;
    private javax.swing.JButton inicioButtonBuscarPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
