/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ProductController;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import Model.Product;
import Model.Category;
import Model.Brand;

/**
 *
 * @author Usuario
 */
public class CrearProductoPanel extends javax.swing.JPanel {

    private MainFrame parentFrame;//
    private final ProductController productController;   // inyección MVC
    private Path selectedImagePath;                      // ruta de la imagen

    public CrearProductoPanel(MainFrame parentFrame,
            ProductController productController) {
        this.parentFrame = parentFrame;
        this.productController = productController;
        initComponents();
    }

    public CrearProductoPanel(MainFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    public void setCrearProductoParentFrame(MainFrame parentFrame) { // <- parámetro correcto
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        BackgroundColorPhotoGaleryDialog = new javax.swing.JPanel();
        BackgroundColorProductFormPanel = new javax.swing.JPanel();
        tituloCrearProductoProductFormPanel = new javax.swing.JLabel();
        etiquetaModeloProductFormPanel = new javax.swing.JLabel();
        etiquetaIDProductFormPanel = new javax.swing.JLabel();
        entradaTextoIDProductoProductFormPanel = new javax.swing.JTextField();
        comboCategoriaBotonProductFormPanel = new javax.swing.JComboBox<>();
        comboModeloBotonProductFormPanel = new javax.swing.JComboBox<>();
        etiquetaCategoriaProductFormPanel1 = new javax.swing.JLabel();
        etiquetaDescripcionFormPanel = new javax.swing.JLabel();
        entradaTextoCanttidadProductFormPanel = new javax.swing.JTextField();
        etiquetaCantidadFormPanel = new javax.swing.JLabel();
        etiquetaPrecioFormPanel = new javax.swing.JLabel();
        entradaTextoDescripcionProductFormPanel = new javax.swing.JTextField();
        entradaTextoPrecioProductFormPanel = new javax.swing.JTextField();
        etiquetaModeloProductFormPanel1 = new javax.swing.JLabel();
        javax.swing.JButton BotonSeleccionarImagenProductFormPanel = new javax.swing.JButton();
        volverButtonCrearProductPanel = new javax.swing.JButton();
        crearProductButtonProductoPanel = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        BackgroundColorPhotoGaleryDialog.setPreferredSize(new java.awt.Dimension(1366, 768));

        BackgroundColorProductFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundColorProductFormPanel.setForeground(new java.awt.Color(255, 255, 255));
        BackgroundColorProductFormPanel.setPreferredSize(new java.awt.Dimension(1366, 768));

        tituloCrearProductoProductFormPanel.setFont(new java.awt.Font("SansSerif", 0, 96)); // NOI18N
        tituloCrearProductoProductFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        tituloCrearProductoProductFormPanel.setText("Crear producto");

        etiquetaModeloProductFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaModeloProductFormPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etiquetaModeloProductFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaModeloProductFormPanel.setText("Seleccionar imagen");

        etiquetaIDProductFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaIDProductFormPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etiquetaIDProductFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaIDProductFormPanel.setText("ID del producto");

        entradaTextoIDProductoProductFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        entradaTextoIDProductoProductFormPanel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        entradaTextoIDProductoProductFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        entradaTextoIDProductoProductFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        entradaTextoIDProductoProductFormPanel.setCaretColor(new java.awt.Color(255, 255, 255));
        entradaTextoIDProductoProductFormPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTextoIDProductoProductFormPanelActionPerformed(evt);
            }
        });

        comboCategoriaBotonProductFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        comboCategoriaBotonProductFormPanel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        comboCategoriaBotonProductFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        comboCategoriaBotonProductFormPanel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monitor", "Accesorios", "Celulares", "Audio", "Gaming" }));
        comboCategoriaBotonProductFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboCategoriaBotonProductFormPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaBotonProductFormPanelActionPerformed(evt);
            }
        });

        comboModeloBotonProductFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        comboModeloBotonProductFormPanel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        comboModeloBotonProductFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        comboModeloBotonProductFormPanel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LG", "Xiaomi", "Asus", "DELL", "Iphone", "Samsung", "Huawei", "AMD", "Redragon", "Astro", "Fury", "Razer", "Intel", "Wooting", "Logitech", "Acer" }));
        comboModeloBotonProductFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboModeloBotonProductFormPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModeloBotonProductFormPanelActionPerformed(evt);
            }
        });

        etiquetaCategoriaProductFormPanel1.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaCategoriaProductFormPanel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etiquetaCategoriaProductFormPanel1.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaCategoriaProductFormPanel1.setText("Categoria");

        etiquetaDescripcionFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaDescripcionFormPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etiquetaDescripcionFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaDescripcionFormPanel.setText("Descripción");

        entradaTextoCanttidadProductFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        entradaTextoCanttidadProductFormPanel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        entradaTextoCanttidadProductFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        entradaTextoCanttidadProductFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        entradaTextoCanttidadProductFormPanel.setCaretColor(new java.awt.Color(255, 255, 255));
        entradaTextoCanttidadProductFormPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTextoCanttidadProductFormPanelActionPerformed(evt);
            }
        });

        etiquetaCantidadFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaCantidadFormPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etiquetaCantidadFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaCantidadFormPanel.setText("Cantidad");

        etiquetaPrecioFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaPrecioFormPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etiquetaPrecioFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaPrecioFormPanel.setText("Precio");

        entradaTextoDescripcionProductFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        entradaTextoDescripcionProductFormPanel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        entradaTextoDescripcionProductFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        entradaTextoDescripcionProductFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        entradaTextoDescripcionProductFormPanel.setCaretColor(new java.awt.Color(255, 255, 255));
        entradaTextoDescripcionProductFormPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTextoDescripcionProductFormPanelActionPerformed(evt);
            }
        });

        entradaTextoPrecioProductFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        entradaTextoPrecioProductFormPanel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        entradaTextoPrecioProductFormPanel.setForeground(new java.awt.Color(0, 0, 0));
        entradaTextoPrecioProductFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        entradaTextoPrecioProductFormPanel.setCaretColor(new java.awt.Color(255, 255, 255));
        entradaTextoPrecioProductFormPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTextoPrecioProductFormPanelActionPerformed(evt);
            }
        });

        etiquetaModeloProductFormPanel1.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaModeloProductFormPanel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etiquetaModeloProductFormPanel1.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaModeloProductFormPanel1.setText("Modelo");

        BotonSeleccionarImagenProductFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        BotonSeleccionarImagenProductFormPanel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BotonSeleccionarImagenProductFormPanel.setForeground(new java.awt.Color(51, 51, 51));
        BotonSeleccionarImagenProductFormPanel.setText("Seleccionar");
        BotonSeleccionarImagenProductFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonSeleccionarImagenProductFormPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSeleccionarImagenProductFormPanelActionPerformed(evt);
            }
        });

        volverButtonCrearProductPanel.setText("Volver");
        volverButtonCrearProductPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonCrearProductPanelActionPerformed(evt);
            }
        });

        crearProductButtonProductoPanel.setText("Crear");
        crearProductButtonProductoPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProductButtonProductoPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundColorProductFormPanelLayout = new javax.swing.GroupLayout(BackgroundColorProductFormPanel);
        BackgroundColorProductFormPanel.setLayout(BackgroundColorProductFormPanelLayout);
        BackgroundColorProductFormPanelLayout.setHorizontalGroup(
            BackgroundColorProductFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                .addGroup(BackgroundColorProductFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(volverButtonCrearProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234)
                        .addComponent(tituloCrearProductoProductFormPanel))
                    .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(etiquetaCategoriaProductFormPanel1)
                        .addGap(452, 452, 452)
                        .addComponent(etiquetaModeloProductFormPanel1))
                    .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(comboCategoriaBotonProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(comboModeloBotonProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(etiquetaDescripcionFormPanel)
                        .addGap(420, 420, 420)
                        .addComponent(etiquetaModeloProductFormPanel))
                    .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(BackgroundColorProductFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaIDProductFormPanel)
                            .addComponent(entradaTextoIDProductoProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(BackgroundColorProductFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaTextoDescripcionProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaPrecioFormPanel)
                            .addComponent(entradaTextoPrecioProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaCantidadFormPanel)
                            .addComponent(entradaTextoCanttidadProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addComponent(BotonSeleccionarImagenProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(crearProductButtonProductoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        BackgroundColorProductFormPanelLayout.setVerticalGroup(
            BackgroundColorProductFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearProductButtonProductoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundColorProductFormPanelLayout.createSequentialGroup()
                .addGroup(BackgroundColorProductFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloCrearProductoProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(volverButtonCrearProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(etiquetaIDProductFormPanel)
                .addGap(6, 6, 6)
                .addComponent(entradaTextoIDProductoProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundColorProductFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaCategoriaProductFormPanel1)
                    .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(etiquetaModeloProductFormPanel1)))
                .addGap(2, 2, 2)
                .addGroup(BackgroundColorProductFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCategoriaBotonProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboModeloBotonProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(BackgroundColorProductFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaDescripcionFormPanel)
                    .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(etiquetaModeloProductFormPanel)))
                .addGap(18, 18, 18)
                .addGroup(BackgroundColorProductFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundColorProductFormPanelLayout.createSequentialGroup()
                        .addComponent(entradaTextoDescripcionProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaPrecioFormPanel)
                        .addGap(25, 25, 25)
                        .addComponent(entradaTextoPrecioProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(etiquetaCantidadFormPanel)
                        .addGap(18, 18, 18)
                        .addComponent(entradaTextoCanttidadProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonSeleccionarImagenProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout BackgroundColorPhotoGaleryDialogLayout = new javax.swing.GroupLayout(BackgroundColorPhotoGaleryDialog);
        BackgroundColorPhotoGaleryDialog.setLayout(BackgroundColorPhotoGaleryDialogLayout);
        BackgroundColorPhotoGaleryDialogLayout.setHorizontalGroup(
            BackgroundColorPhotoGaleryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundColorPhotoGaleryDialogLayout.createSequentialGroup()
                .addComponent(BackgroundColorProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BackgroundColorPhotoGaleryDialogLayout.setVerticalGroup(
            BackgroundColorPhotoGaleryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundColorPhotoGaleryDialogLayout.createSequentialGroup()
                .addComponent(BackgroundColorProductFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundColorPhotoGaleryDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundColorPhotoGaleryDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entradaTextoIDProductoProductFormPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaTextoIDProductoProductFormPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaTextoIDProductoProductFormPanelActionPerformed

    private void comboCategoriaBotonProductFormPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaBotonProductFormPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriaBotonProductFormPanelActionPerformed

    private void comboModeloBotonProductFormPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModeloBotonProductFormPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboModeloBotonProductFormPanelActionPerformed

    private void entradaTextoCanttidadProductFormPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaTextoCanttidadProductFormPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaTextoCanttidadProductFormPanelActionPerformed

    private void entradaTextoDescripcionProductFormPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaTextoDescripcionProductFormPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaTextoDescripcionProductFormPanelActionPerformed

    private void entradaTextoPrecioProductFormPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaTextoPrecioProductFormPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaTextoPrecioProductFormPanelActionPerformed

    private void BotonSeleccionarImagenProductFormPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSeleccionarImagenProductFormPanelActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Selecciona imagen del producto");
        fc.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imágenes (JPG, PNG)", "jpg", "jpeg", "png"));

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selectedImagePath = fc.getSelectedFile().toPath();
        }
    }//GEN-LAST:event_BotonSeleccionarImagenProductFormPanelActionPerformed

    private void volverButtonCrearProductPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonCrearProductPanelActionPerformed
        if (parentFrame != null) {
            parentFrame.showCard(MainFrame.ADMIN_CARD);
        } else {
            System.err.println("Error: No se ha establecido referencia al MainFrame");
        }
    }//GEN-LAST:event_volverButtonCrearProductPanelActionPerformed

    private void crearProductButtonProductoPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductButtonProductoPanelActionPerformed
        // TODO add your handling code here:
        String id = entradaTextoIDProductoProductFormPanel.getText().trim();
        String categoria = (String) comboCategoriaBotonProductFormPanel.getSelectedItem();
        String modelo = (String) comboModeloBotonProductFormPanel.getSelectedItem();
        String desc = entradaTextoDescripcionProductFormPanel.getText().trim();
        String precioStr = entradaTextoPrecioProductFormPanel.getText().trim();
        String cantStr = entradaTextoCanttidadProductFormPanel.getText().trim();

        if (id.isEmpty() || categoria == null || modelo == null
                || desc.isEmpty() || precioStr.isEmpty() || cantStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Todos los campos son obligatorios.",
                    "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double precio;
        int cantidad;
        try {
            precio = Double.parseDouble(precioStr);
            cantidad = Integer.parseInt(cantStr);
            if (precio < 0 || cantidad < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Precio y cantidad deben ser números positivos.",
                    "Validación", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- Construir el producto ---
        Product p = new Product();
        p.setId(id);
        p.setName(modelo + " " + categoria); // ejemplo simple de nombre
        p.setDescription(desc);
        p.setCategory(new Category(categoria.toLowerCase(), categoria));
        p.setBrand(new Brand(modelo));
        p.setPrice(precio);
        p.setQuantity(cantidad);

        // --- Guardar imagen (opcional) ---
        try {
            if (selectedImagePath != null) {
                Path destino = productController.saveImage(selectedImagePath);
                p.setImagePath(destino.toString());
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al copiar la imagen:\n" + ex.getMessage(),
                    "Imagen", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- Persiste con el controlador ---
        boolean ok = productController.addProduct(p);
        if (ok) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Producto creado correctamente.",
                    "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            limpiarFormulario();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo crear el producto (¿ID duplicado?).",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_crearProductButtonProductoPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundColorPhotoGaleryDialog;
    private javax.swing.JPanel BackgroundColorProductFormPanel;
    private javax.swing.JComboBox<String> comboCategoriaBotonProductFormPanel;
    private javax.swing.JComboBox<String> comboModeloBotonProductFormPanel;
    private javax.swing.JButton crearProductButtonProductoPanel;
    private javax.swing.JTextField entradaTextoCanttidadProductFormPanel;
    private javax.swing.JTextField entradaTextoDescripcionProductFormPanel;
    private javax.swing.JTextField entradaTextoIDProductoProductFormPanel;
    private javax.swing.JTextField entradaTextoPrecioProductFormPanel;
    private javax.swing.JLabel etiquetaCantidadFormPanel;
    private javax.swing.JLabel etiquetaCategoriaProductFormPanel1;
    private javax.swing.JLabel etiquetaDescripcionFormPanel;
    private javax.swing.JLabel etiquetaIDProductFormPanel;
    private javax.swing.JLabel etiquetaModeloProductFormPanel;
    private javax.swing.JLabel etiquetaModeloProductFormPanel1;
    private javax.swing.JLabel etiquetaPrecioFormPanel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel tituloCrearProductoProductFormPanel;
    private javax.swing.JButton volverButtonCrearProductPanel;
    // End of variables declaration//GEN-END:variables

    private void limpiarFormulario() {
        entradaTextoIDProductoProductFormPanel.setText("");
        comboCategoriaBotonProductFormPanel.setSelectedIndex(-1);
        comboModeloBotonProductFormPanel.setSelectedIndex(-1);
        entradaTextoDescripcionProductFormPanel.setText("");
        entradaTextoPrecioProductFormPanel.setText("");
        entradaTextoCanttidadProductFormPanel.setText("");
        selectedImagePath = null;

    }
}
