/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Personal
 */
public class EditarImagenPanel extends javax.swing.JPanel {
    private MainFrame parentFrame;

    /**
     * Creates new form editImagenDialog
     */
    public EditarImagenPanel() {
        initComponents();
    }
    public EditarImagenPanel(MainFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    public void setEditarImagenParentFrame(MainFrame parentMainFrame) {
        this.parentFrame = parentFrame;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabelDialog_editImagenDialog = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cambiarButtonEditImagenPanel = new javax.swing.JButton();
        guardarImagenButtonPanel = new javax.swing.JButton();
        volverButtonEditarImagenPanel = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 768));

        titleLabelDialog_editImagenDialog.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titleLabelDialog_editImagenDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabelDialog_editImagenDialog.setText("Editar imagen");
        titleLabelDialog_editImagenDialog.setPreferredSize(new java.awt.Dimension(334, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("imagen");
        jLabel1.setPreferredSize(new java.awt.Dimension(1130, 505));

        cambiarButtonEditImagenPanel.setText("Cambiar");
        cambiarButtonEditImagenPanel.setPreferredSize(new java.awt.Dimension(290, 75));
        cambiarButtonEditImagenPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarButtonEditImagenPanelActionPerformed(evt);
            }
        });

        guardarImagenButtonPanel.setText("Guardar");
        guardarImagenButtonPanel.setPreferredSize(new java.awt.Dimension(290, 75));
        guardarImagenButtonPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarImagenButtonPanelActionPerformed(evt);
            }
        });

        volverButtonEditarImagenPanel.setText("Volver");
        volverButtonEditarImagenPanel.setPreferredSize(new java.awt.Dimension(290, 75));
        volverButtonEditarImagenPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonEditarImagenPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 186, Short.MAX_VALUE)
                .addComponent(cambiarButtonEditImagenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(guardarImagenButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(volverButtonEditarImagenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLabelDialog_editImagenDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(501, 501, 501))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(titleLabelDialog_editImagenDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverButtonEditarImagenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarImagenButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiarButtonEditImagenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarButtonEditImagenPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarButtonEditImagenPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarButtonEditImagenPanelActionPerformed

    private void guardarImagenButtonPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarImagenButtonPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarImagenButtonPanelActionPerformed

    private void volverButtonEditarImagenPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonEditarImagenPanelActionPerformed
        if (parentFrame != null) {
            parentFrame.showCard(MainFrame.ADMIN_CARD);
        } else {
            System.err.println("Error: No se ha establecido referencia al MainFrame");
        }
    }//GEN-LAST:event_volverButtonEditarImagenPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarButtonEditImagenPanel;
    private javax.swing.JButton guardarImagenButtonPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel titleLabelDialog_editImagenDialog;
    private javax.swing.JButton volverButtonEditarImagenPanel;
    // End of variables declaration//GEN-END:variables
}
