/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;



/**
 *
 * @author Usuario
 */
public class LoginPanel extends javax.swing.JPanel {
    private MainFrame parentFrame;

    /**
     * Panel de inicio de sesión Botones "Cliente" y "Administrador"
     */
    public LoginPanel(MainFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        logoPrismaShopLoginPanel = new javax.swing.JLabel();
        imageIconPrismaLoginPanel = new javax.swing.JLabel();
        userLoginClienteButton = new javax.swing.JButton();
        userLoginAdminButton = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        logoPrismaShopLoginPanel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        logoPrismaShopLoginPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoPrismaShopLoginPanel.setText("PrismaShop");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(100, 88, 0, 0);
        jPanel1.add(logoPrismaShopLoginPanel, gridBagConstraints);

        imageIconPrismaLoginPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        imageIconPrismaLoginPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageIconPrismaLoginPanel.setText("LOGO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(277, 143, 0, 0);
        jPanel1.add(imageIconPrismaLoginPanel, gridBagConstraints);

        userLoginClienteButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userLoginClienteButton.setText("Iniciar como cliente");
        userLoginClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginClienteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(158, 232, 350, 0);
        jPanel1.add(userLoginClienteButton, gridBagConstraints);

        userLoginAdminButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userLoginAdminButton.setText("Iniciar como Admin");
        userLoginAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginAdminButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(158, 84, 350, 366);
        jPanel1.add(userLoginAdminButton, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userLoginAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginAdminButtonActionPerformed
       parentFrame.showCard(MainFrame.ADMIN_CARD);
    }//GEN-LAST:event_userLoginAdminButtonActionPerformed

    private void userLoginClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userLoginClienteButtonActionPerformed
        parentFrame.showCard(MainFrame.MENU_CLIENTE_CARD);
 
    }// GEN-LAST:event_userLoginClienteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageIconPrismaLoginPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoPrismaShopLoginPanel;
    private javax.swing.JButton userLoginAdminButton;
    private javax.swing.JButton userLoginClienteButton;
    // End of variables declaration//GEN-END:variables

}
