/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.CardLayout;

/**
 *
 * @author Usuario
 */
public class MainFrame extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private LoginPanel loginPanel;
    private MainMenuCliente mainMenuCliente;
    private ProductDetailPanel productDetailPanel;
    private ProductDetailPanelGaming productDetailPanelGaming;
    private ProductDetailPanelAudio productDetailPanelAudio;
    private ProductDetailPanelCelulares productDetailPanelCelulares;
    private ProductDetailPanelAccesorios productDetailPanelAccesorios;
    private AdminPanel adminPanel;
    private CrearProductoPanel crearProductoPanel;
    private BuscarProductoPanel buscarProductoPanel;
    private EditarImagenPanel editarImagenPanel;
   
    public static final String MAIN_CARD = "main";
    public static final String LOGIN_CARD = "Login";
    public static final String MENU_CLIENTE_CARD = "Menu Cliente";
    public static final String MONITOR_PRODUCT_CARD = "Monitores";
    public static final String GAMING_PRODUCTS_CARD = "Gaming";
    public static final String AUDIO_PRODUCT_CARD = "Audio";
    public static final String CELULARES_PRODUCT_CARD = "Celulares";
    public static final String ACCESORIOS_PRODUCT_CARD = "Accesorios";
    public static final String ADMIN_CARD = "Admin Panel";
    public static final String CREAR_PRODUCTO_CARD = "Crear Producto";
    public static final String BUSCAR_PRODUCTO_CARD = "Buscar Producto";
    public static final String EDITAR_IMAGEN_CARD = "Editar Imagen";
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setupCardLayout();
    }

    private void setupCardLayout() {
        cardLayout = new CardLayout();
        getContentPane().setLayout(cardLayout);
        loginPanel = new LoginPanel(this);
        mainMenuCliente = new MainMenuCliente(this);
        productDetailPanelGaming = new ProductDetailPanelGaming(this);
        productDetailPanel = new ProductDetailPanel(this);
        productDetailPanelAudio = new ProductDetailPanelAudio(this);
        productDetailPanelAccesorios = new ProductDetailPanelAccesorios(this);
        productDetailPanelCelulares = new ProductDetailPanelCelulares(this);
        adminPanel = new AdminPanel(this);
        crearProductoPanel = new CrearProductoPanel(this);
        buscarProductoPanel = new BuscarProductoPanel(this);
        editarImagenPanel = new EditarImagenPanel(this);
        
        getContentPane().add(editarImagenPanel, EDITAR_IMAGEN_CARD);
        getContentPane().add(buscarProductoPanel, BUSCAR_PRODUCTO_CARD);
        getContentPane().add(crearProductoPanel, CREAR_PRODUCTO_CARD);
        getContentPane().add(adminPanel, ADMIN_CARD);
        getContentPane().add(MainFramePanel, MAIN_CARD);
        getContentPane().add(loginPanel, LOGIN_CARD);
        getContentPane().add(mainMenuCliente, MENU_CLIENTE_CARD);
        getContentPane().add(productDetailPanel, MONITOR_PRODUCT_CARD);
        getContentPane().add(productDetailPanelAudio, AUDIO_PRODUCT_CARD);
        getContentPane().add(productDetailPanelGaming, GAMING_PRODUCTS_CARD);
        getContentPane().add(productDetailPanelCelulares, CELULARES_PRODUCT_CARD);
        getContentPane().add(productDetailPanelAccesorios, ACCESORIOS_PRODUCT_CARD);

        cardLayout.show(getContentPane(), MAIN_CARD);
    }

    public void showCard(String cardName) {
        cardLayout.show(getContentPane(), cardName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFramePanel = new javax.swing.JPanel();
        EntrarButtonMainFrame = new javax.swing.JButton();
        LogoMainFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainFramePanel.setPreferredSize(new java.awt.Dimension(1366, 768));

        EntrarButtonMainFrame.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        EntrarButtonMainFrame.setText("Entrar");
        EntrarButtonMainFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarButtonMainFrameActionPerformed(evt);
            }
        });

        LogoMainFrame.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        LogoMainFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoMainFrame.setText("PrismaShop");

        javax.swing.GroupLayout MainFramePanelLayout = new javax.swing.GroupLayout(MainFramePanel);
        MainFramePanel.setLayout(MainFramePanelLayout);
        MainFramePanelLayout.setHorizontalGroup(
            MainFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainFramePanelLayout.createSequentialGroup()
                .addGroup(MainFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainFramePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoMainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainFramePanelLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(EntrarButtonMainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainFramePanelLayout.setVerticalGroup(
            MainFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainFramePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LogoMainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EntrarButtonMainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(MainFramePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(MainFramePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarButtonMainFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarButtonMainFrameActionPerformed
        showCard(LOGIN_CARD);
    }//GEN-LAST:event_EntrarButtonMainFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EntrarButtonMainFrame;
    private javax.swing.JLabel LogoMainFrame;
    private javax.swing.JPanel MainFramePanel;
    // End of variables declaration//GEN-END:variables
}
