/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;


/**
 *
 * @author Usuario
 */
public class MainMenuCliente extends javax.swing.JPanel {
            private MainFrame parentFrame;
    /**
     * Menú principal con categorías Sidebar de navegación Área de búsqueda
     */
    public MainMenuCliente(MainFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MonitoresButtonMainMenuCliente = new javax.swing.JButton();
        accesoriosButtonMenuCliente = new javax.swing.JButton();
        celularesButtonMainMenuCliente = new javax.swing.JButton();
        audioButtonMainMenuCliente = new javax.swing.JButton();
        gamingButtonMainMenuCliente = new javax.swing.JButton();
        PanelDestacadoMainMenu = new javax.swing.JPanel();
        MonitoresImageLabelMainMenu = new javax.swing.JLabel();
        MonitoresLabelLetraMainMenu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        audioImageMainMenu = new javax.swing.JLabel();
        celularesLetraLabelMainMenu = new javax.swing.JLabel();
        audioLetraLabelMainMenu = new javax.swing.JLabel();
        celularesImageLabelMainMenu = new javax.swing.JLabel();
        accesoriosImageMainMenu = new javax.swing.JLabel();
        accesoriosLetraLabelMainMenu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        logoPrismaMainMenuPanel = new javax.swing.JLabel();
        prismaShopMainMenu = new javax.swing.JLabel();
        BuscarButtonMainMenu = new javax.swing.JButton();
        reloggButtonMainMenu = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1368, 768));

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Image1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Image2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Image3");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Image4");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Image5");

        MonitoresButtonMainMenuCliente.setBackground(new java.awt.Color(204, 204, 204));
        MonitoresButtonMainMenuCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MonitoresButtonMainMenuCliente.setForeground(new java.awt.Color(30, 30, 30));
        MonitoresButtonMainMenuCliente.setText("Monitores");
        MonitoresButtonMainMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonitoresButtonMainMenuClienteActionPerformed(evt);
            }
        });

        accesoriosButtonMenuCliente.setBackground(new java.awt.Color(204, 204, 204));
        accesoriosButtonMenuCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accesoriosButtonMenuCliente.setForeground(new java.awt.Color(30, 30, 30));
        accesoriosButtonMenuCliente.setText("Accesorios");
        accesoriosButtonMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoriosButtonMenuClienteActionPerformed(evt);
            }
        });

        celularesButtonMainMenuCliente.setBackground(new java.awt.Color(204, 204, 204));
        celularesButtonMainMenuCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        celularesButtonMainMenuCliente.setForeground(new java.awt.Color(30, 30, 30));
        celularesButtonMainMenuCliente.setText("Celulares");
        celularesButtonMainMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularesButtonMainMenuClienteActionPerformed(evt);
            }
        });

        audioButtonMainMenuCliente.setBackground(new java.awt.Color(204, 204, 204));
        audioButtonMainMenuCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        audioButtonMainMenuCliente.setForeground(new java.awt.Color(30, 30, 30));
        audioButtonMainMenuCliente.setText("Audio");
        audioButtonMainMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioButtonMainMenuClienteActionPerformed(evt);
            }
        });

        gamingButtonMainMenuCliente.setBackground(new java.awt.Color(204, 204, 204));
        gamingButtonMainMenuCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gamingButtonMainMenuCliente.setForeground(new java.awt.Color(30, 30, 30));
        gamingButtonMainMenuCliente.setText("Gaming");
        gamingButtonMainMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamingButtonMainMenuClienteActionPerformed(evt);
            }
        });

        PanelDestacadoMainMenu.setPreferredSize(new java.awt.Dimension(1093, 768));

        MonitoresImageLabelMainMenu.setForeground(new java.awt.Color(255, 255, 255));

        MonitoresLabelLetraMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MonitoresLabelLetraMainMenu.setText("Monitores");

        celularesLetraLabelMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        celularesLetraLabelMainMenu.setText("Celulares");

        audioLetraLabelMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        audioLetraLabelMainMenu.setText("Audio");

        accesoriosLetraLabelMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accesoriosLetraLabelMainMenu.setText("Accesorios");

        javax.swing.GroupLayout PanelDestacadoMainMenuLayout = new javax.swing.GroupLayout(PanelDestacadoMainMenu);
        PanelDestacadoMainMenu.setLayout(PanelDestacadoMainMenuLayout);
        PanelDestacadoMainMenuLayout.setHorizontalGroup(
            PanelDestacadoMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                .addGroup(PanelDestacadoMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jLabel7))
                    .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                        .addGroup(PanelDestacadoMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(MonitoresLabelLetraMainMenu))
                            .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(MonitoresImageLabelMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(celularesImageLabelMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(celularesLetraLabelMainMenu)))
                        .addGroup(PanelDestacadoMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                                .addGap(505, 505, 505)
                                .addGroup(PanelDestacadoMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelDestacadoMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(accesoriosImageMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDestacadoMainMenuLayout.createSequentialGroup()
                                            .addGap(49, 49, 49)
                                            .addComponent(accesoriosLetraLabelMainMenu)
                                            .addGap(64, 64, 64)))
                                    .addComponent(audioImageMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDestacadoMainMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(audioLetraLabelMainMenu)
                                .addGap(83, 83, 83)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        PanelDestacadoMainMenuLayout.setVerticalGroup(
            PanelDestacadoMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PanelDestacadoMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MonitoresImageLabelMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accesoriosImageMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDestacadoMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MonitoresLabelLetraMainMenu)
                    .addComponent(accesoriosLetraLabelMainMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDestacadoMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                        .addComponent(audioImageMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioLetraLabelMainMenu))
                    .addGroup(PanelDestacadoMainMenuLayout.createSequentialGroup()
                        .addComponent(celularesImageLabelMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(celularesLetraLabelMainMenu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Destacado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MonitoresButtonMainMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accesoriosButtonMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(celularesButtonMainMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(audioButtonMainMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gamingButtonMainMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelDestacadoMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1117, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonitoresButtonMainMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accesoriosButtonMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celularesButtonMainMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(audioButtonMainMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamingButtonMainMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDestacadoMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
        );

        logoPrismaMainMenuPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logoPrismaMainMenuPanel.setText("LOGO");

        prismaShopMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        prismaShopMainMenu.setText("PrismaShop");

        BuscarButtonMainMenu.setBackground(new java.awt.Color(204, 204, 204));
        BuscarButtonMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BuscarButtonMainMenu.setForeground(new java.awt.Color(30, 30, 30));
        BuscarButtonMainMenu.setText("Buscar");
        BuscarButtonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarButtonMainMenuActionPerformed(evt);
            }
        });

        reloggButtonMainMenu.setBackground(new java.awt.Color(204, 204, 204));
        reloggButtonMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reloggButtonMainMenu.setForeground(new java.awt.Color(30, 30, 30));
        reloggButtonMainMenu.setText("Reloggear");
        reloggButtonMainMenu.setPreferredSize(new java.awt.Dimension(103, 43));
        reloggButtonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloggButtonMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoPrismaMainMenuPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prismaShopMainMenu)
                        .addGap(520, 520, 520)
                        .addComponent(BuscarButtonMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reloggButtonMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoPrismaMainMenuPanel)
                    .addComponent(prismaShopMainMenu)
                    .addComponent(BuscarButtonMainMenu)
                    .addComponent(reloggButtonMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MonitoresButtonMainMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonitoresButtonMainMenuClienteActionPerformed
        parentFrame.showCard(MainFrame.MONITOR_PRODUCT_CARD);
    }//GEN-LAST:event_MonitoresButtonMainMenuClienteActionPerformed

    private void BuscarButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarButtonMainMenuActionPerformed
       parentFrame.showCard(MainFrame.BUSCAR_PRODUCTO_CARD);
    }//GEN-LAST:event_BuscarButtonMainMenuActionPerformed

    private void accesoriosButtonMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoriosButtonMenuClienteActionPerformed
       parentFrame.showCard(MainFrame.ACCESORIOS_PRODUCT_CARD);
    }//GEN-LAST:event_accesoriosButtonMenuClienteActionPerformed

    private void celularesButtonMainMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularesButtonMainMenuClienteActionPerformed
        parentFrame.showCard(MainFrame.CELULARES_PRODUCT_CARD);
    }//GEN-LAST:event_celularesButtonMainMenuClienteActionPerformed

    private void audioButtonMainMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioButtonMainMenuClienteActionPerformed
        parentFrame.showCard(MainFrame.AUDIO_PRODUCT_CARD);
    }//GEN-LAST:event_audioButtonMainMenuClienteActionPerformed

    private void gamingButtonMainMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamingButtonMainMenuClienteActionPerformed
        parentFrame.showCard(MainFrame.GAMING_PRODUCTS_CARD);
    }//GEN-LAST:event_gamingButtonMainMenuClienteActionPerformed

    private void reloggButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloggButtonMainMenuActionPerformed
       parentFrame.showCard(MainFrame.LOGIN_CARD);
    }//GEN-LAST:event_reloggButtonMainMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarButtonMainMenu;
    private javax.swing.JButton MonitoresButtonMainMenuCliente;
    private javax.swing.JLabel MonitoresImageLabelMainMenu;
    private javax.swing.JLabel MonitoresLabelLetraMainMenu;
    private javax.swing.JPanel PanelDestacadoMainMenu;
    private javax.swing.JButton accesoriosButtonMenuCliente;
    private javax.swing.JLabel accesoriosImageMainMenu;
    private javax.swing.JLabel accesoriosLetraLabelMainMenu;
    private javax.swing.JButton audioButtonMainMenuCliente;
    private javax.swing.JLabel audioImageMainMenu;
    private javax.swing.JLabel audioLetraLabelMainMenu;
    private javax.swing.JButton celularesButtonMainMenuCliente;
    private javax.swing.JLabel celularesImageLabelMainMenu;
    private javax.swing.JLabel celularesLetraLabelMainMenu;
    private javax.swing.JButton gamingButtonMainMenuCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoPrismaMainMenuPanel;
    private javax.swing.JLabel prismaShopMainMenu;
    private javax.swing.JButton reloggButtonMainMenu;
    // End of variables declaration//GEN-END:variables
}
