/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * Función: Panel para mostrar un producto disponible Componentes:Imagen grande,
 * descripción completa, precio, cantidad disponible
 */
public class ProductDetailPanel extends javax.swing.JPanel {
    private MainFrame parentFrame;

    /**
     * Creates new form ProductDetailPanel
     */
    public ProductDetailPanel() {
        initComponents();
    }

    public ProductDetailPanel(MainFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    public void setParentFrame(MainFrame parentMainFrame) {
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonInicio = new javax.swing.JButton();
        etiquetaProductosDisponibles = new javax.swing.JLabel();
        ProductoMonitor1 = new javax.swing.JPanel();
        imagenProductoMonitorProductDetailPanel1 = new javax.swing.JLabel();
        CategoriaAndModeloTituloMonitor1 = new javax.swing.JLabel();
        DescripcionMonitor1 = new javax.swing.JLabel();
        precioMonitor1 = new javax.swing.JLabel();
        stockMonitor1 = new javax.swing.JLabel();
        ProductoMonitor2 = new javax.swing.JPanel();
        imagenProductoMonitorProductDetailPanel2 = new javax.swing.JLabel();
        CategoriaAndModeloTituloMonitor2 = new javax.swing.JLabel();
        DescripcionMonitor2 = new javax.swing.JLabel();
        precioMonitor2 = new javax.swing.JLabel();
        precioMonitor4 = new javax.swing.JLabel();
        stockMonitor2 = new javax.swing.JLabel();
        ProductoMonitor3 = new javax.swing.JPanel();
        imagenProductoMonitorProductDetailPanel3 = new javax.swing.JLabel();
        CategoriaAndModeloTituloMonitor3 = new javax.swing.JLabel();
        DescripcionMonitor3 = new javax.swing.JLabel();
        precioMonitor3 = new javax.swing.JLabel();
        precioMonitor5 = new javax.swing.JLabel();
        stockMonitor3 = new javax.swing.JLabel();
        ProductoMonitor4 = new javax.swing.JPanel();
        imagenProductoMonitorProductDetailPanel4 = new javax.swing.JLabel();
        CategoriaAndModeloTituloMonitor4 = new javax.swing.JLabel();
        DescripcionMonitor4 = new javax.swing.JLabel();
        precioMonitor6 = new javax.swing.JLabel();
        stockMonitor4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1440, 1040));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        BotonInicio.setText("Inicio");
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        etiquetaProductosDisponibles.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        etiquetaProductosDisponibles.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaProductosDisponibles.setText("¡Productos disponibles!");

        ProductoMonitor1.setBackground(new java.awt.Color(219, 219, 219));
        ProductoMonitor1.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoMonitorProductDetailPanel1.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoMonitorProductDetailPanel1.setText("foto");

        CategoriaAndModeloTituloMonitor1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloMonitor1.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloMonitor1.setText("Monitor Curvo LG");

        DescripcionMonitor1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionMonitor1.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMonitor1.setText("Monitor Curvo LG Ultragear QHD De 34\" 34GP63A, HDR 10,AMD Freesync Premium, 160 Hz");
        DescripcionMonitor1.setToolTipText("");
        DescripcionMonitor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioMonitor1.setForeground(new java.awt.Color(0, 0, 0));
        precioMonitor1.setText("Precio:  ₡714,699");

        stockMonitor1.setForeground(new java.awt.Color(0, 0, 0));
        stockMonitor1.setText("Cantidad: 4");

        javax.swing.GroupLayout ProductoMonitor1Layout = new javax.swing.GroupLayout(ProductoMonitor1);
        ProductoMonitor1.setLayout(ProductoMonitor1Layout);
        ProductoMonitor1Layout.setHorizontalGroup(
            ProductoMonitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoMonitor1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(ProductoMonitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoMonitor1Layout.createSequentialGroup()
                        .addComponent(imagenProductoMonitorProductDetailPanel1)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoMonitor1Layout.createSequentialGroup()
                        .addGroup(ProductoMonitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CategoriaAndModeloTituloMonitor1)
                            .addComponent(DescripcionMonitor1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
            .addGroup(ProductoMonitor1Layout.createSequentialGroup()
                .addGroup(ProductoMonitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoMonitor1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(precioMonitor1))
                    .addGroup(ProductoMonitor1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(stockMonitor1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ProductoMonitor1Layout.setVerticalGroup(
            ProductoMonitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoMonitor1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoMonitorProductDetailPanel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(CategoriaAndModeloTituloMonitor1)
                .addGap(30, 30, 30)
                .addComponent(DescripcionMonitor1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(precioMonitor1)
                .addGap(29, 29, 29)
                .addComponent(stockMonitor1)
                .addGap(96, 96, 96))
        );

        ProductoMonitor2.setBackground(new java.awt.Color(219, 219, 219));
        ProductoMonitor2.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoMonitorProductDetailPanel2.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoMonitorProductDetailPanel2.setText("foto");

        CategoriaAndModeloTituloMonitor2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloMonitor2.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloMonitor2.setText("Monitor Xiaomi");

        DescripcionMonitor2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionMonitor2.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMonitor2.setText("Monitor XIaomi A22i / 48343");
        DescripcionMonitor2.setToolTipText("");
        DescripcionMonitor2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioMonitor2.setForeground(new java.awt.Color(0, 0, 0));
        precioMonitor2.setText("jLabel1");

        precioMonitor4.setForeground(new java.awt.Color(0, 0, 0));
        precioMonitor4.setText("Precio: ₡425,000");

        stockMonitor2.setForeground(new java.awt.Color(0, 0, 0));
        stockMonitor2.setText("Cantidad: 9");

        javax.swing.GroupLayout ProductoMonitor2Layout = new javax.swing.GroupLayout(ProductoMonitor2);
        ProductoMonitor2.setLayout(ProductoMonitor2Layout);
        ProductoMonitor2Layout.setHorizontalGroup(
            ProductoMonitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoMonitor2Layout.createSequentialGroup()
                .addGroup(ProductoMonitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoMonitor2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoMonitorProductDetailPanel2))
                    .addGroup(ProductoMonitor2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(ProductoMonitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precioMonitor4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoMonitor2Layout.createSequentialGroup()
                                .addComponent(stockMonitor2)
                                .addGap(21, 21, 21)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoMonitor2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(ProductoMonitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescripcionMonitor2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoriaAndModeloTituloMonitor2))
                .addGap(35, 35, 35))
        );
        ProductoMonitor2Layout.setVerticalGroup(
            ProductoMonitor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoMonitor2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoMonitorProductDetailPanel2)
                .addGap(97, 97, 97)
                .addComponent(CategoriaAndModeloTituloMonitor2)
                .addGap(12, 12, 12)
                .addComponent(DescripcionMonitor2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precioMonitor4)
                .addGap(32, 32, 32)
                .addComponent(stockMonitor2)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        ProductoMonitor3.setBackground(new java.awt.Color(219, 219, 219));
        ProductoMonitor3.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoMonitorProductDetailPanel3.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoMonitorProductDetailPanel3.setText("foto");

        CategoriaAndModeloTituloMonitor3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloMonitor3.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloMonitor3.setText("MONITOR ASUS");

        DescripcionMonitor3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionMonitor3.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMonitor3.setText("MONITOR ASUS 27 VA27EHEY/VZ279");
        DescripcionMonitor3.setToolTipText("");
        DescripcionMonitor3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioMonitor3.setForeground(new java.awt.Color(0, 0, 0));
        precioMonitor3.setText("jLabel1");

        precioMonitor5.setForeground(new java.awt.Color(0, 0, 0));
        precioMonitor5.setText("Precio: ₡846,990");

        stockMonitor3.setForeground(new java.awt.Color(0, 0, 0));
        stockMonitor3.setText("Cantidad: 13");

        javax.swing.GroupLayout ProductoMonitor3Layout = new javax.swing.GroupLayout(ProductoMonitor3);
        ProductoMonitor3.setLayout(ProductoMonitor3Layout);
        ProductoMonitor3Layout.setHorizontalGroup(
            ProductoMonitor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoMonitor3Layout.createSequentialGroup()
                .addGroup(ProductoMonitor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoMonitor3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoMonitorProductDetailPanel3))
                    .addGroup(ProductoMonitor3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(CategoriaAndModeloTituloMonitor3))
                    .addGroup(ProductoMonitor3Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(ProductoMonitor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductoMonitor3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(stockMonitor3))
                            .addComponent(precioMonitor5))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(ProductoMonitor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProductoMonitor3Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(DescripcionMonitor3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        ProductoMonitor3Layout.setVerticalGroup(
            ProductoMonitor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoMonitor3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoMonitorProductDetailPanel3)
                .addGap(99, 99, 99)
                .addComponent(CategoriaAndModeloTituloMonitor3)
                .addGap(31, 31, 31)
                .addComponent(precioMonitor5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockMonitor3)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(ProductoMonitor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProductoMonitor3Layout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addComponent(DescripcionMonitor3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );

        ProductoMonitor4.setBackground(new java.awt.Color(219, 219, 219));
        ProductoMonitor4.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoMonitorProductDetailPanel4.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoMonitorProductDetailPanel4.setText("foto");

        CategoriaAndModeloTituloMonitor4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloMonitor4.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloMonitor4.setText("MONITOR DELL");

        DescripcionMonitor4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionMonitor4.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMonitor4.setText("MONITOR DELL CURVED GAMING 24P");
        DescripcionMonitor4.setToolTipText("");
        DescripcionMonitor4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioMonitor6.setForeground(new java.awt.Color(0, 0, 0));
        precioMonitor6.setText("Precio: ₡446,990");

        stockMonitor4.setForeground(new java.awt.Color(0, 0, 0));
        stockMonitor4.setText("Cantidad: 4");

        javax.swing.GroupLayout ProductoMonitor4Layout = new javax.swing.GroupLayout(ProductoMonitor4);
        ProductoMonitor4.setLayout(ProductoMonitor4Layout);
        ProductoMonitor4Layout.setHorizontalGroup(
            ProductoMonitor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoMonitor4Layout.createSequentialGroup()
                .addGroup(ProductoMonitor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoMonitor4Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoMonitorProductDetailPanel4))
                    .addGroup(ProductoMonitor4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(CategoriaAndModeloTituloMonitor4))
                    .addGroup(ProductoMonitor4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(DescripcionMonitor4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoMonitor4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ProductoMonitor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoMonitor4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(stockMonitor4))
                    .addComponent(precioMonitor6))
                .addGap(90, 90, 90))
        );
        ProductoMonitor4Layout.setVerticalGroup(
            ProductoMonitor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoMonitor4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoMonitorProductDetailPanel4)
                .addGap(100, 100, 100)
                .addComponent(CategoriaAndModeloTituloMonitor4)
                .addGap(9, 9, 9)
                .addComponent(DescripcionMonitor4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(precioMonitor6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockMonitor4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(etiquetaProductosDisponibles)))
                .addContainerGap(423, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ProductoMonitor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(ProductoMonitor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ProductoMonitor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(ProductoMonitor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etiquetaProductosDisponibles)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductoMonitor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoMonitor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoMonitor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ProductoMonitor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        if (parentFrame != null) {
            parentFrame.showCard(MainFrame.MENU_CLIENTE_CARD);
        } else {
            System.err.println("Error: No se ha establecido referencia al MainFrame");
        }
    }//GEN-LAST:event_BotonInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JLabel CategoriaAndModeloTituloMonitor1;
    private javax.swing.JLabel CategoriaAndModeloTituloMonitor2;
    private javax.swing.JLabel CategoriaAndModeloTituloMonitor3;
    private javax.swing.JLabel CategoriaAndModeloTituloMonitor4;
    private javax.swing.JLabel DescripcionMonitor1;
    private javax.swing.JLabel DescripcionMonitor2;
    private javax.swing.JLabel DescripcionMonitor3;
    private javax.swing.JLabel DescripcionMonitor4;
    private javax.swing.JPanel ProductoMonitor1;
    private javax.swing.JPanel ProductoMonitor2;
    private javax.swing.JPanel ProductoMonitor3;
    private javax.swing.JPanel ProductoMonitor4;
    private javax.swing.JLabel etiquetaProductosDisponibles;
    private javax.swing.JLabel imagenProductoMonitorProductDetailPanel1;
    private javax.swing.JLabel imagenProductoMonitorProductDetailPanel2;
    private javax.swing.JLabel imagenProductoMonitorProductDetailPanel3;
    private javax.swing.JLabel imagenProductoMonitorProductDetailPanel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel precioMonitor1;
    private javax.swing.JLabel precioMonitor2;
    private javax.swing.JLabel precioMonitor3;
    private javax.swing.JLabel precioMonitor4;
    private javax.swing.JLabel precioMonitor5;
    private javax.swing.JLabel precioMonitor6;
    private javax.swing.JLabel stockMonitor1;
    private javax.swing.JLabel stockMonitor2;
    private javax.swing.JLabel stockMonitor3;
    private javax.swing.JLabel stockMonitor4;
    // End of variables declaration//GEN-END:variables
}
