/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * Función: Panel para mostrar un producto disponible Componentes:Imagen grande,
 * descripción completa, precio, cantidad disponible
 */
public class ProductDetailPanelAccesorios extends javax.swing.JPanel {

    private MainFrame parentFrame;

    /**
     * Creates new form ProductDetailPanel
     */
    public ProductDetailPanelAccesorios() {
        initComponents();
    }

    public ProductDetailPanelAccesorios(MainFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    public void setAccesoriosParentFrame(MainFrame parentMainFrame) {
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonInicio = new javax.swing.JButton();
        etiquetaProductosDisponibles = new javax.swing.JLabel();
        ProductoAccesorios1 = new javax.swing.JPanel();
        imagenProductoAccesoriosProductDetailPanel1 = new javax.swing.JLabel();
        CategoriaAndModeloTituloAccesorios1 = new javax.swing.JLabel();
        DescripcionAccesorios1 = new javax.swing.JLabel();
        precioAccesorio1 = new javax.swing.JLabel();
        stockAccesorios1 = new javax.swing.JLabel();
        ProductoAccesorios2 = new javax.swing.JPanel();
        imagenProductoAccesoriosProductDetailPanel2 = new javax.swing.JLabel();
        CategoriaAndModeloTituloMonitor2 = new javax.swing.JLabel();
        DescripcionAccesorios2 = new javax.swing.JLabel();
        precioAccesorio2 = new javax.swing.JLabel();
        stockMonitor3 = new javax.swing.JLabel();
        ProductoAccesorios3 = new javax.swing.JPanel();
        imagenProductoAccesoriosProductDetailPanel3 = new javax.swing.JLabel();
        CategoriaAndModeloTituloMonitor3 = new javax.swing.JLabel();
        DescripcionAccesorios4 = new javax.swing.JLabel();
        precioAccesorio3 = new javax.swing.JLabel();
        stockMonitor4 = new javax.swing.JLabel();
        ProductoAccesorios4 = new javax.swing.JPanel();
        imagenProductoAccesoriosProductDetailPanel4 = new javax.swing.JLabel();
        CategoriaAndModeloTituloMonitor4 = new javax.swing.JLabel();
        DescripcionAccesorios3 = new javax.swing.JLabel();
        precioAccesorio4 = new javax.swing.JLabel();
        stockMonitor5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        BotonInicio.setText("Inicio");
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        etiquetaProductosDisponibles.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        etiquetaProductosDisponibles.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaProductosDisponibles.setText("¡Productos disponibles!");

        ProductoAccesorios1.setBackground(new java.awt.Color(219, 219, 219));
        ProductoAccesorios1.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoAccesoriosProductDetailPanel1.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoAccesoriosProductDetailPanel1.setText("foto");

        CategoriaAndModeloTituloAccesorios1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloAccesorios1.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloAccesorios1.setText("Adaptador");

        DescripcionAccesorios1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionAccesorios1.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionAccesorios1.setText("Adaptador USB-C a HDMI + carga");
        DescripcionAccesorios1.setToolTipText("");
        DescripcionAccesorios1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAccesorio1.setForeground(new java.awt.Color(0, 0, 0));
        precioAccesorio1.setText("Precio:  ₡30,000");

        stockAccesorios1.setForeground(new java.awt.Color(0, 0, 0));
        stockAccesorios1.setText("Cantidad: 4");

        javax.swing.GroupLayout ProductoAccesorios1Layout = new javax.swing.GroupLayout(ProductoAccesorios1);
        ProductoAccesorios1.setLayout(ProductoAccesorios1Layout);
        ProductoAccesorios1Layout.setHorizontalGroup(
            ProductoAccesorios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAccesorios1Layout.createSequentialGroup()
                .addGroup(ProductoAccesorios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoAccesorios1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoAccesoriosProductDetailPanel1))
                    .addGroup(ProductoAccesorios1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(ProductoAccesorios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescripcionAccesorios1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CategoriaAndModeloTituloAccesorios1)))
                    .addGroup(ProductoAccesorios1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(ProductoAccesorios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockAccesorios1)
                            .addComponent(precioAccesorio1))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        ProductoAccesorios1Layout.setVerticalGroup(
            ProductoAccesorios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAccesorios1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoAccesoriosProductDetailPanel1)
                .addGap(110, 110, 110)
                .addComponent(CategoriaAndModeloTituloAccesorios1)
                .addGap(27, 27, 27)
                .addComponent(DescripcionAccesorios1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioAccesorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stockAccesorios1)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        ProductoAccesorios2.setBackground(new java.awt.Color(219, 219, 219));
        ProductoAccesorios2.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoAccesoriosProductDetailPanel2.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoAccesoriosProductDetailPanel2.setText("foto");

        CategoriaAndModeloTituloMonitor2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloMonitor2.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloMonitor2.setText("MEMORIA USB");

        DescripcionAccesorios2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionAccesorios2.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionAccesorios2.setText("MEMORIA USB SANDISK ULTRA DUAL DRIVE LUXE USB-C – 1TB");
        DescripcionAccesorios2.setToolTipText("");
        DescripcionAccesorios2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAccesorio2.setForeground(new java.awt.Color(0, 0, 0));
        precioAccesorio2.setText("Precio: ₡70,000");

        stockMonitor3.setForeground(new java.awt.Color(0, 0, 0));
        stockMonitor3.setText("Cantidad: 10");

        javax.swing.GroupLayout ProductoAccesorios2Layout = new javax.swing.GroupLayout(ProductoAccesorios2);
        ProductoAccesorios2.setLayout(ProductoAccesorios2Layout);
        ProductoAccesorios2Layout.setHorizontalGroup(
            ProductoAccesorios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAccesorios2Layout.createSequentialGroup()
                .addGroup(ProductoAccesorios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoAccesorios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ProductoAccesorios2Layout.createSequentialGroup()
                            .addComponent(DescripcionAccesorios2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43))
                        .addGroup(ProductoAccesorios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductoAccesorios2Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(imagenProductoAccesoriosProductDetailPanel2))
                            .addGroup(ProductoAccesorios2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(CategoriaAndModeloTituloMonitor2)))
                        .addGroup(ProductoAccesorios2Layout.createSequentialGroup()
                            .addComponent(precioAccesorio2)
                            .addGap(55, 55, 55)))
                    .addGroup(ProductoAccesorios2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(stockMonitor3)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        ProductoAccesorios2Layout.setVerticalGroup(
            ProductoAccesorios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAccesorios2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoAccesoriosProductDetailPanel2)
                .addGap(105, 105, 105)
                .addComponent(CategoriaAndModeloTituloMonitor2)
                .addGap(30, 30, 30)
                .addComponent(DescripcionAccesorios2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precioAccesorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stockMonitor3)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        ProductoAccesorios3.setBackground(new java.awt.Color(219, 219, 219));
        ProductoAccesorios3.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoAccesoriosProductDetailPanel3.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoAccesoriosProductDetailPanel3.setText("foto");

        CategoriaAndModeloTituloMonitor3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloMonitor3.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloMonitor3.setText("Base ventilada");

        DescripcionAccesorios4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionAccesorios4.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionAccesorios4.setText("Base ventilada para laptop ajustable con bandeja para mouse");
        DescripcionAccesorios4.setToolTipText("");
        DescripcionAccesorios4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAccesorio3.setForeground(new java.awt.Color(0, 0, 0));
        precioAccesorio3.setText("Precio: ₡19,990");

        stockMonitor4.setForeground(new java.awt.Color(0, 0, 0));
        stockMonitor4.setText("Cantidad: 8");

        javax.swing.GroupLayout ProductoAccesorios3Layout = new javax.swing.GroupLayout(ProductoAccesorios3);
        ProductoAccesorios3.setLayout(ProductoAccesorios3Layout);
        ProductoAccesorios3Layout.setHorizontalGroup(
            ProductoAccesorios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAccesorios3Layout.createSequentialGroup()
                .addGroup(ProductoAccesorios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoAccesorios3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoAccesoriosProductDetailPanel3))
                    .addGroup(ProductoAccesorios3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(CategoriaAndModeloTituloMonitor3)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAccesorios3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ProductoAccesorios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stockMonitor4)
                    .addComponent(precioAccesorio3))
                .addGap(107, 107, 107))
            .addGroup(ProductoAccesorios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAccesorios3Layout.createSequentialGroup()
                    .addContainerGap(44, Short.MAX_VALUE)
                    .addComponent(DescripcionAccesorios4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(32, 32, 32)))
        );
        ProductoAccesorios3Layout.setVerticalGroup(
            ProductoAccesorios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAccesorios3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoAccesoriosProductDetailPanel3)
                .addGap(91, 91, 91)
                .addComponent(CategoriaAndModeloTituloMonitor3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(precioAccesorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockMonitor4)
                .addGap(80, 80, 80))
            .addGroup(ProductoAccesorios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAccesorios3Layout.createSequentialGroup()
                    .addContainerGap(239, Short.MAX_VALUE)
                    .addComponent(DescripcionAccesorios4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(169, 169, 169)))
        );

        ProductoAccesorios4.setBackground(new java.awt.Color(219, 219, 219));
        ProductoAccesorios4.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoAccesoriosProductDetailPanel4.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoAccesoriosProductDetailPanel4.setText("foto");

        CategoriaAndModeloTituloMonitor4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloMonitor4.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloMonitor4.setText("Disco duro externo");

        DescripcionAccesorios3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionAccesorios3.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionAccesorios3.setText("Disco duro externo de 1 TB Conexión USB 3.0");
        DescripcionAccesorios3.setToolTipText("");
        DescripcionAccesorios3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAccesorio4.setForeground(new java.awt.Color(0, 0, 0));
        precioAccesorio4.setText("Precio: ₡76,990");

        stockMonitor5.setForeground(new java.awt.Color(0, 0, 0));
        stockMonitor5.setText("Cantidad: 12");

        javax.swing.GroupLayout ProductoAccesorios4Layout = new javax.swing.GroupLayout(ProductoAccesorios4);
        ProductoAccesorios4.setLayout(ProductoAccesorios4Layout);
        ProductoAccesorios4Layout.setHorizontalGroup(
            ProductoAccesorios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAccesorios4Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(imagenProductoAccesoriosProductDetailPanel4)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAccesorios4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProductoAccesorios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAccesorios4Layout.createSequentialGroup()
                        .addGroup(ProductoAccesorios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DescripcionAccesorios3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CategoriaAndModeloTituloMonitor4))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAccesorios4Layout.createSequentialGroup()
                        .addGroup(ProductoAccesorios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stockMonitor5)
                            .addComponent(precioAccesorio4))
                        .addGap(124, 124, 124))))
        );
        ProductoAccesorios4Layout.setVerticalGroup(
            ProductoAccesorios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAccesorios4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoAccesoriosProductDetailPanel4)
                .addGap(91, 91, 91)
                .addComponent(CategoriaAndModeloTituloMonitor4)
                .addGap(52, 52, 52)
                .addComponent(DescripcionAccesorios3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioAccesorio4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockMonitor5)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(etiquetaProductosDisponibles))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ProductoAccesorios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(ProductoAccesorios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(ProductoAccesorios3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(ProductoAccesorios4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaProductosDisponibles)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductoAccesorios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductoAccesorios3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductoAccesorios4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductoAccesorios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        if (parentFrame != null) {
            parentFrame.showCard(MainFrame.MENU_CLIENTE_CARD);
        } else {
            System.err.println("Error: No se ha establecido referencia al MainFrame");
        }
    }//GEN-LAST:event_BotonInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JLabel CategoriaAndModeloTituloAccesorios1;
    private javax.swing.JLabel CategoriaAndModeloTituloMonitor2;
    private javax.swing.JLabel CategoriaAndModeloTituloMonitor3;
    private javax.swing.JLabel CategoriaAndModeloTituloMonitor4;
    private javax.swing.JLabel DescripcionAccesorios1;
    private javax.swing.JLabel DescripcionAccesorios2;
    private javax.swing.JLabel DescripcionAccesorios3;
    private javax.swing.JLabel DescripcionAccesorios4;
    private javax.swing.JPanel ProductoAccesorios1;
    private javax.swing.JPanel ProductoAccesorios2;
    private javax.swing.JPanel ProductoAccesorios3;
    private javax.swing.JPanel ProductoAccesorios4;
    private javax.swing.JLabel etiquetaProductosDisponibles;
    private javax.swing.JLabel imagenProductoAccesoriosProductDetailPanel1;
    private javax.swing.JLabel imagenProductoAccesoriosProductDetailPanel2;
    private javax.swing.JLabel imagenProductoAccesoriosProductDetailPanel3;
    private javax.swing.JLabel imagenProductoAccesoriosProductDetailPanel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel precioAccesorio1;
    private javax.swing.JLabel precioAccesorio2;
    private javax.swing.JLabel precioAccesorio3;
    private javax.swing.JLabel precioAccesorio4;
    private javax.swing.JLabel stockAccesorios1;
    private javax.swing.JLabel stockMonitor3;
    private javax.swing.JLabel stockMonitor4;
    private javax.swing.JLabel stockMonitor5;
    // End of variables declaration//GEN-END:variables
}
