/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * Función: Panel para mostrar un producto disponible Componentes:Imagen grande,
 * descripción completa, precio, cantidad disponible
 */

public class ProductDetailPanelAudio extends javax.swing.JPanel {
    private MainFrame parentFrame;

    /**
     * Creates new form ProductDetailPanel
     */
    public ProductDetailPanelAudio() {
        initComponents();
    }

    public ProductDetailPanelAudio(MainFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    public void setAudioParentFrame(MainFrame parentMainFrame) {
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonInicio = new javax.swing.JButton();
        etiquetaProductosDisponibles = new javax.swing.JLabel();
        ProductoAudio1 = new javax.swing.JPanel();
        imagenProductoAudioProductDetailPanel1 = new javax.swing.JLabel();
        CategoriaAndModeloTituloAudio1 = new javax.swing.JLabel();
        DescripcionAudio1 = new javax.swing.JLabel();
        precioAudio1 = new javax.swing.JLabel();
        stockAudio1 = new javax.swing.JLabel();
        ProductoAudio2 = new javax.swing.JPanel();
        imagenProductoAudioProductDetailPanel2 = new javax.swing.JLabel();
        CategoriaAndModeloTituloAudio2 = new javax.swing.JLabel();
        DescripcionAudio2 = new javax.swing.JLabel();
        precioAudio2 = new javax.swing.JLabel();
        stockAudio2 = new javax.swing.JLabel();
        ProductoAudio3 = new javax.swing.JPanel();
        imagenProductoAudioProductDetailPanel3 = new javax.swing.JLabel();
        CategoriaAndModeloTituloAudio3 = new javax.swing.JLabel();
        DescripcionAudio3 = new javax.swing.JLabel();
        precioAudio3 = new javax.swing.JLabel();
        stockAudio3 = new javax.swing.JLabel();
        ProductoAudio4 = new javax.swing.JPanel();
        imagenProductoAudioProductDetailPanel4 = new javax.swing.JLabel();
        CategoriaAndModeloTituloAudio4 = new javax.swing.JLabel();
        DescripcionAudio4 = new javax.swing.JLabel();
        precioAudio4 = new javax.swing.JLabel();
        stockAudio4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1440, 1040));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        BotonInicio.setText("Inicio");
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        etiquetaProductosDisponibles.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        etiquetaProductosDisponibles.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaProductosDisponibles.setText("¡Productos disponibles!");

        ProductoAudio1.setBackground(new java.awt.Color(219, 219, 219));
        ProductoAudio1.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoAudioProductDetailPanel1.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoAudioProductDetailPanel1.setText("foto");

        CategoriaAndModeloTituloAudio1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloAudio1.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloAudio1.setText("Redragon Echowav");

        DescripcionAudio1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionAudio1.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionAudio1.setText("Micrófono de estudio con iluminación RGB");
        DescripcionAudio1.setToolTipText("");
        DescripcionAudio1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAudio1.setForeground(new java.awt.Color(0, 0, 0));
        precioAudio1.setText("Precio:  ₡25,000");

        stockAudio1.setForeground(new java.awt.Color(0, 0, 0));
        stockAudio1.setText("Cantidad: 7");

        javax.swing.GroupLayout ProductoAudio1Layout = new javax.swing.GroupLayout(ProductoAudio1);
        ProductoAudio1.setLayout(ProductoAudio1Layout);
        ProductoAudio1Layout.setHorizontalGroup(
            ProductoAudio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAudio1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(ProductoAudio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAudio1Layout.createSequentialGroup()
                        .addGroup(ProductoAudio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CategoriaAndModeloTituloAudio1)
                            .addComponent(DescripcionAudio1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAudio1Layout.createSequentialGroup()
                        .addComponent(precioAudio1)
                        .addGap(118, 118, 118))))
            .addGroup(ProductoAudio1Layout.createSequentialGroup()
                .addGroup(ProductoAudio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoAudio1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoAudioProductDetailPanel1))
                    .addGroup(ProductoAudio1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(stockAudio1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProductoAudio1Layout.setVerticalGroup(
            ProductoAudio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAudio1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoAudioProductDetailPanel1)
                .addGap(102, 102, 102)
                .addComponent(CategoriaAndModeloTituloAudio1)
                .addGap(33, 33, 33)
                .addComponent(DescripcionAudio1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(precioAudio1)
                .addGap(35, 35, 35)
                .addComponent(stockAudio1)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        ProductoAudio2.setBackground(new java.awt.Color(219, 219, 219));
        ProductoAudio2.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoAudioProductDetailPanel2.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoAudioProductDetailPanel2.setText("foto");

        CategoriaAndModeloTituloAudio2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloAudio2.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloAudio2.setText("Redragon Orphe");

        DescripcionAudio2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionAudio2.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionAudio2.setText("2 x Parlantes Stereo / Barra de Sonido ");
        DescripcionAudio2.setToolTipText("");
        DescripcionAudio2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAudio2.setForeground(new java.awt.Color(0, 0, 0));
        precioAudio2.setText("Precio: ₡53,000");

        stockAudio2.setForeground(new java.awt.Color(0, 0, 0));
        stockAudio2.setText("Cantidad: 7");

        javax.swing.GroupLayout ProductoAudio2Layout = new javax.swing.GroupLayout(ProductoAudio2);
        ProductoAudio2.setLayout(ProductoAudio2Layout);
        ProductoAudio2Layout.setHorizontalGroup(
            ProductoAudio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAudio2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(precioAudio2)
                .addGap(118, 118, 118))
            .addGroup(ProductoAudio2Layout.createSequentialGroup()
                .addGroup(ProductoAudio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoAudio2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoAudioProductDetailPanel2))
                    .addGroup(ProductoAudio2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(ProductoAudio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescripcionAudio2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CategoriaAndModeloTituloAudio2)))
                    .addGroup(ProductoAudio2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(stockAudio2)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        ProductoAudio2Layout.setVerticalGroup(
            ProductoAudio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAudio2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoAudioProductDetailPanel2)
                .addGap(102, 102, 102)
                .addComponent(CategoriaAndModeloTituloAudio2)
                .addGap(30, 30, 30)
                .addComponent(DescripcionAudio2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(precioAudio2)
                .addGap(38, 38, 38)
                .addComponent(stockAudio2)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        ProductoAudio3.setBackground(new java.awt.Color(219, 219, 219));
        ProductoAudio3.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoAudioProductDetailPanel3.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoAudioProductDetailPanel3.setText("foto");

        CategoriaAndModeloTituloAudio3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloAudio3.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloAudio3.setText("Parlante UNNO TEK");

        DescripcionAudio3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionAudio3.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionAudio3.setText("Altavoz activo autoamplificado de 5″ (2)  Bluetooth© 5.0");
        DescripcionAudio3.setToolTipText("");
        DescripcionAudio3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAudio3.setForeground(new java.awt.Color(0, 0, 0));
        precioAudio3.setText("Precio: ₡31,300");

        stockAudio3.setForeground(new java.awt.Color(0, 0, 0));
        stockAudio3.setText("Cantidad: 8");

        javax.swing.GroupLayout ProductoAudio3Layout = new javax.swing.GroupLayout(ProductoAudio3);
        ProductoAudio3.setLayout(ProductoAudio3Layout);
        ProductoAudio3Layout.setHorizontalGroup(
            ProductoAudio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAudio3Layout.createSequentialGroup()
                .addGroup(ProductoAudio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoAudio3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoAudioProductDetailPanel3))
                    .addGroup(ProductoAudio3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(CategoriaAndModeloTituloAudio3))
                    .addGroup(ProductoAudio3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(DescripcionAudio3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductoAudio3Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(precioAudio3)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAudio3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(stockAudio3)
                .addGap(130, 130, 130))
        );
        ProductoAudio3Layout.setVerticalGroup(
            ProductoAudio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAudio3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoAudioProductDetailPanel3)
                .addGap(103, 103, 103)
                .addComponent(CategoriaAndModeloTituloAudio3)
                .addGap(30, 30, 30)
                .addComponent(DescripcionAudio3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precioAudio3)
                .addGap(41, 41, 41)
                .addComponent(stockAudio3)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        ProductoAudio4.setBackground(new java.awt.Color(219, 219, 219));
        ProductoAudio4.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoAudioProductDetailPanel4.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoAudioProductDetailPanel4.setText("foto");

        CategoriaAndModeloTituloAudio4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloAudio4.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloAudio4.setText("Parlante UNNO TEK ");

        DescripcionAudio4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionAudio4.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionAudio4.setText("La BeatBox es tan compacta pero a la vez tan potente. ");
        DescripcionAudio4.setToolTipText("");
        DescripcionAudio4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAudio4.setForeground(new java.awt.Color(0, 0, 0));
        precioAudio4.setText("Precio: ₡340,000");

        stockAudio4.setForeground(new java.awt.Color(0, 0, 0));
        stockAudio4.setText("Cantidad: 2");

        javax.swing.GroupLayout ProductoAudio4Layout = new javax.swing.GroupLayout(ProductoAudio4);
        ProductoAudio4.setLayout(ProductoAudio4Layout);
        ProductoAudio4Layout.setHorizontalGroup(
            ProductoAudio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoAudio4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(precioAudio4)
                .addGap(128, 128, 128))
            .addGroup(ProductoAudio4Layout.createSequentialGroup()
                .addGroup(ProductoAudio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoAudio4Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(imagenProductoAudioProductDetailPanel4))
                    .addGroup(ProductoAudio4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(CategoriaAndModeloTituloAudio4))
                    .addGroup(ProductoAudio4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(DescripcionAudio4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductoAudio4Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(stockAudio4)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        ProductoAudio4Layout.setVerticalGroup(
            ProductoAudio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoAudio4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(imagenProductoAudioProductDetailPanel4)
                .addGap(94, 94, 94)
                .addComponent(CategoriaAndModeloTituloAudio4)
                .addGap(36, 36, 36)
                .addComponent(DescripcionAudio4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioAudio4)
                .addGap(45, 45, 45)
                .addComponent(stockAudio4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(etiquetaProductosDisponibles))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(ProductoAudio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductoAudio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductoAudio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProductoAudio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaProductosDisponibles)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductoAudio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoAudio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoAudio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoAudio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        if (parentFrame != null) {
            parentFrame.showCard(MainFrame.MENU_CLIENTE_CARD);
        } else {
            System.err.println("Error: No se ha establecido referencia al MainFrame");
        }
    
    }//GEN-LAST:event_BotonInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JLabel CategoriaAndModeloTituloAudio1;
    private javax.swing.JLabel CategoriaAndModeloTituloAudio2;
    private javax.swing.JLabel CategoriaAndModeloTituloAudio3;
    private javax.swing.JLabel CategoriaAndModeloTituloAudio4;
    private javax.swing.JLabel DescripcionAudio1;
    private javax.swing.JLabel DescripcionAudio2;
    private javax.swing.JLabel DescripcionAudio3;
    private javax.swing.JLabel DescripcionAudio4;
    private javax.swing.JPanel ProductoAudio1;
    private javax.swing.JPanel ProductoAudio2;
    private javax.swing.JPanel ProductoAudio3;
    private javax.swing.JPanel ProductoAudio4;
    private javax.swing.JLabel etiquetaProductosDisponibles;
    private javax.swing.JLabel imagenProductoAudioProductDetailPanel1;
    private javax.swing.JLabel imagenProductoAudioProductDetailPanel2;
    private javax.swing.JLabel imagenProductoAudioProductDetailPanel3;
    private javax.swing.JLabel imagenProductoAudioProductDetailPanel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel precioAudio1;
    private javax.swing.JLabel precioAudio2;
    private javax.swing.JLabel precioAudio3;
    private javax.swing.JLabel precioAudio4;
    private javax.swing.JLabel stockAudio1;
    private javax.swing.JLabel stockAudio2;
    private javax.swing.JLabel stockAudio3;
    private javax.swing.JLabel stockAudio4;
    // End of variables declaration//GEN-END:variables
}
