/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * Función: Panel para mostrar un producto disponible Componentes:Imagen grande,
 * descripción completa, precio, cantidad disponible
 */
public class ProductDetailPanelGaming extends javax.swing.JPanel {

    private MainFrame parentFrame;

    /**
     * Creates new form ProductDetailPanel
     */
    public ProductDetailPanelGaming() {
        initComponents();
    }

    public ProductDetailPanelGaming(MainFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    public void setGamingParentFrame(MainFrame parentMainFrame) {
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonInicio = new javax.swing.JButton();
        etiquetaProductosDisponibles = new javax.swing.JLabel();
        ProductoGaming1 = new javax.swing.JPanel();
        imagenProductoGamingProductDetailPanel1 = new javax.swing.JLabel();
        CategoriaAndModeloTituloGaming1 = new javax.swing.JLabel();
        DescripcionGaming1 = new javax.swing.JLabel();
        precioGaming1 = new javax.swing.JLabel();
        stockGaming1 = new javax.swing.JLabel();
        ProductoGaming2 = new javax.swing.JPanel();
        imagenProductoGamingProductDetailPanel2 = new javax.swing.JLabel();
        CategoriaAndModeloTituloGaming2 = new javax.swing.JLabel();
        DescripcionGaming2 = new javax.swing.JLabel();
        precioAudio4 = new javax.swing.JLabel();
        stockGaming2 = new javax.swing.JLabel();
        ProductoGaming3 = new javax.swing.JPanel();
        imagenProductoGamingProductDetailPanel3 = new javax.swing.JLabel();
        CategoriaAndModeloTituloGaming3 = new javax.swing.JLabel();
        DescripcionGaming3 = new javax.swing.JLabel();
        precioAudio5 = new javax.swing.JLabel();
        stockGaming3 = new javax.swing.JLabel();
        ProductoGaming4 = new javax.swing.JPanel();
        imagenProductoGamingProductDetailPanel4 = new javax.swing.JLabel();
        CategoriaAndModeloTituloGaming4 = new javax.swing.JLabel();
        DescripcionGaming4 = new javax.swing.JLabel();
        precioAudio6 = new javax.swing.JLabel();
        stockGaming4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1440, 1040));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));

        BotonInicio.setText("Inicio");
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        etiquetaProductosDisponibles.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        etiquetaProductosDisponibles.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaProductosDisponibles.setText("¡Productos disponibles!");

        ProductoGaming1.setBackground(new java.awt.Color(219, 219, 219));
        ProductoGaming1.setForeground(new java.awt.Color(237, 237, 237));
        ProductoGaming1.setPreferredSize(new java.awt.Dimension(300, 300));

        imagenProductoGamingProductDetailPanel1.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoGamingProductDetailPanel1.setText("foto");

        CategoriaAndModeloTituloGaming1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CategoriaAndModeloTituloGaming1.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloGaming1.setText("SapphirePulse AMD ");

        DescripcionGaming1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        DescripcionGaming1.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionGaming1.setText("Tarjeta Grafica para videojuegos con 24gb de memoria.");
        DescripcionGaming1.setToolTipText("");
        DescripcionGaming1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioGaming1.setForeground(new java.awt.Color(0, 0, 0));
        precioGaming1.setText("Precio:  ₡609,000");

        stockGaming1.setForeground(new java.awt.Color(0, 0, 0));
        stockGaming1.setText("Cantidad: 2");

        javax.swing.GroupLayout ProductoGaming1Layout = new javax.swing.GroupLayout(ProductoGaming1);
        ProductoGaming1.setLayout(ProductoGaming1Layout);
        ProductoGaming1Layout.setHorizontalGroup(
            ProductoGaming1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoGaming1Layout.createSequentialGroup()
                .addGroup(ProductoGaming1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DescripcionGaming1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProductoGaming1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ProductoGaming1Layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(imagenProductoGamingProductDetailPanel1))
                        .addGroup(ProductoGaming1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(CategoriaAndModeloTituloGaming1))
                        .addGroup(ProductoGaming1Layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addGroup(ProductoGaming1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(precioGaming1)
                                .addComponent(stockGaming1)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        ProductoGaming1Layout.setVerticalGroup(
            ProductoGaming1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoGaming1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(imagenProductoGamingProductDetailPanel1)
                .addGap(111, 111, 111)
                .addComponent(CategoriaAndModeloTituloGaming1)
                .addGap(18, 18, 18)
                .addComponent(DescripcionGaming1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(precioGaming1)
                .addGap(18, 18, 18)
                .addComponent(stockGaming1)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        ProductoGaming2.setBackground(new java.awt.Color(219, 219, 219));
        ProductoGaming2.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoGamingProductDetailPanel2.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoGamingProductDetailPanel2.setText("foto");

        CategoriaAndModeloTituloGaming2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CategoriaAndModeloTituloGaming2.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloGaming2.setText("Teclado + Mouse");

        DescripcionGaming2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionGaming2.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionGaming2.setText("Teclado y mouse RedDragon k552");
        DescripcionGaming2.setToolTipText("");
        DescripcionGaming2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAudio4.setForeground(new java.awt.Color(0, 0, 0));
        precioAudio4.setText("Precio: ₡35,000");

        stockGaming2.setForeground(new java.awt.Color(0, 0, 0));
        stockGaming2.setText("Cantidad: 15");

        javax.swing.GroupLayout ProductoGaming2Layout = new javax.swing.GroupLayout(ProductoGaming2);
        ProductoGaming2.setLayout(ProductoGaming2Layout);
        ProductoGaming2Layout.setHorizontalGroup(
            ProductoGaming2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoGaming2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(imagenProductoGamingProductDetailPanel2)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoGaming2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProductoGaming2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoGaming2Layout.createSequentialGroup()
                        .addComponent(CategoriaAndModeloTituloGaming2)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoGaming2Layout.createSequentialGroup()
                        .addGroup(ProductoGaming2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stockGaming2)
                            .addComponent(precioAudio4))
                        .addGap(127, 127, 127))))
            .addGroup(ProductoGaming2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProductoGaming2Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(DescripcionGaming2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        ProductoGaming2Layout.setVerticalGroup(
            ProductoGaming2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoGaming2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(imagenProductoGamingProductDetailPanel2)
                .addGap(106, 106, 106)
                .addComponent(CategoriaAndModeloTituloGaming2)
                .addGap(65, 65, 65)
                .addComponent(precioAudio4)
                .addGap(30, 30, 30)
                .addComponent(stockGaming2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ProductoGaming2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProductoGaming2Layout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(DescripcionGaming2)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );

        ProductoGaming3.setBackground(new java.awt.Color(219, 219, 219));
        ProductoGaming3.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoGamingProductDetailPanel3.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoGamingProductDetailPanel3.setText("foto");

        CategoriaAndModeloTituloGaming3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CategoriaAndModeloTituloGaming3.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloGaming3.setText("Headphones Astro");

        DescripcionGaming3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionGaming3.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionGaming3.setText("Astro A50 X - Lightspeed Wireless + Base Station-Blanco");
        DescripcionGaming3.setToolTipText("");
        DescripcionGaming3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAudio5.setForeground(new java.awt.Color(0, 0, 0));
        precioAudio5.setText("Precio: ₡182,300");

        stockGaming3.setForeground(new java.awt.Color(0, 0, 0));
        stockGaming3.setText("Cantidad: 19");

        javax.swing.GroupLayout ProductoGaming3Layout = new javax.swing.GroupLayout(ProductoGaming3);
        ProductoGaming3.setLayout(ProductoGaming3Layout);
        ProductoGaming3Layout.setHorizontalGroup(
            ProductoGaming3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoGaming3Layout.createSequentialGroup()
                .addGroup(ProductoGaming3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoGaming3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(imagenProductoGamingProductDetailPanel3))
                    .addGroup(ProductoGaming3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(CategoriaAndModeloTituloGaming3)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoGaming3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ProductoGaming3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stockGaming3)
                    .addComponent(precioAudio5))
                .addGap(126, 126, 126))
            .addGroup(ProductoGaming3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProductoGaming3Layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(DescripcionGaming3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );
        ProductoGaming3Layout.setVerticalGroup(
            ProductoGaming3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoGaming3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(imagenProductoGamingProductDetailPanel3)
                .addGap(103, 103, 103)
                .addComponent(CategoriaAndModeloTituloGaming3)
                .addGap(72, 72, 72)
                .addComponent(precioAudio5)
                .addGap(18, 18, 18)
                .addComponent(stockGaming3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(ProductoGaming3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProductoGaming3Layout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(DescripcionGaming3)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );

        ProductoGaming4.setBackground(new java.awt.Color(219, 219, 219));
        ProductoGaming4.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoGamingProductDetailPanel4.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoGamingProductDetailPanel4.setText("foto");

        CategoriaAndModeloTituloGaming4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CategoriaAndModeloTituloGaming4.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloGaming4.setText("Fury Design Pc");

        DescripcionGaming4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionGaming4.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionGaming4.setText("Procesador: Intel Core i5 14600K,16gb ram, Rtx 3060 12gb ");
        DescripcionGaming4.setToolTipText("");
        DescripcionGaming4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAudio6.setForeground(new java.awt.Color(0, 0, 0));
        precioAudio6.setText("Precio: ₡340,000");

        stockGaming4.setForeground(new java.awt.Color(0, 0, 0));
        stockGaming4.setText("Cantidad:20");

        javax.swing.GroupLayout ProductoGaming4Layout = new javax.swing.GroupLayout(ProductoGaming4);
        ProductoGaming4.setLayout(ProductoGaming4Layout);
        ProductoGaming4Layout.setHorizontalGroup(
            ProductoGaming4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoGaming4Layout.createSequentialGroup()
                .addGroup(ProductoGaming4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoGaming4Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(imagenProductoGamingProductDetailPanel4))
                    .addGroup(ProductoGaming4Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(CategoriaAndModeloTituloGaming4))
                    .addGroup(ProductoGaming4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(DescripcionGaming4))
                    .addGroup(ProductoGaming4Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(ProductoGaming4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precioAudio6)
                            .addComponent(stockGaming4))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        ProductoGaming4Layout.setVerticalGroup(
            ProductoGaming4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoGaming4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(imagenProductoGamingProductDetailPanel4)
                .addGap(111, 111, 111)
                .addComponent(CategoriaAndModeloTituloGaming4)
                .addGap(30, 30, 30)
                .addComponent(DescripcionGaming4)
                .addGap(37, 37, 37)
                .addComponent(precioAudio6)
                .addGap(18, 18, 18)
                .addComponent(stockGaming4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductoGaming1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductoGaming2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProductoGaming3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductoGaming4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(etiquetaProductosDisponibles)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaProductosDisponibles)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductoGaming2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoGaming3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoGaming4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoGaming1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        if (parentFrame != null) {
            parentFrame.showCard(MainFrame.MENU_CLIENTE_CARD);
        } else {
            System.err.println("Error: No se ha establecido referencia al MainFrame");
        }
    }//GEN-LAST:event_BotonInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JLabel CategoriaAndModeloTituloGaming1;
    private javax.swing.JLabel CategoriaAndModeloTituloGaming2;
    private javax.swing.JLabel CategoriaAndModeloTituloGaming3;
    private javax.swing.JLabel CategoriaAndModeloTituloGaming4;
    private javax.swing.JLabel DescripcionGaming1;
    private javax.swing.JLabel DescripcionGaming2;
    private javax.swing.JLabel DescripcionGaming3;
    private javax.swing.JLabel DescripcionGaming4;
    private javax.swing.JPanel ProductoGaming1;
    private javax.swing.JPanel ProductoGaming2;
    private javax.swing.JPanel ProductoGaming3;
    private javax.swing.JPanel ProductoGaming4;
    private javax.swing.JLabel etiquetaProductosDisponibles;
    private javax.swing.JLabel imagenProductoGamingProductDetailPanel1;
    private javax.swing.JLabel imagenProductoGamingProductDetailPanel2;
    private javax.swing.JLabel imagenProductoGamingProductDetailPanel3;
    private javax.swing.JLabel imagenProductoGamingProductDetailPanel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel precioAudio4;
    private javax.swing.JLabel precioAudio5;
    private javax.swing.JLabel precioAudio6;
    private javax.swing.JLabel precioGaming1;
    private javax.swing.JLabel stockGaming1;
    private javax.swing.JLabel stockGaming2;
    private javax.swing.JLabel stockGaming3;
    private javax.swing.JLabel stockGaming4;
    // End of variables declaration//GEN-END:variables
}
