/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * Función: Panel para mostrar un producto disponible Componentes:Imagen grande,
 * descripción completa, precio, cantidad disponible
 */
public class ProductDetailPanelCelulares extends javax.swing.JPanel {

    private MainFrame parentFrame;

    /**
     * Creates new form ProductDetailPanel
     */
    public ProductDetailPanelCelulares() {
        initComponents();
    }

    public ProductDetailPanelCelulares(MainFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    public void setCelularesParentFrame(MainFrame parentMainFrame) {
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonInicio = new javax.swing.JButton();
        etiquetaProductosDisponibles = new javax.swing.JLabel();
        ProductoCelulares1 = new javax.swing.JPanel();
        imagenProductoCelularesProductDetailPanel1 = new javax.swing.JLabel();
        CategoriaAndModeloTituloCelulares1 = new javax.swing.JLabel();
        DescripcionCelulares1 = new javax.swing.JLabel();
        precioCelulares1 = new javax.swing.JLabel();
        stockCelulares1 = new javax.swing.JLabel();
        ProductoCelulares2 = new javax.swing.JPanel();
        imagenProductoCelularesProductDetailPanel2 = new javax.swing.JLabel();
        CategoriaAndModeloTituloMonitor2 = new javax.swing.JLabel();
        DescripcionCelulares2 = new javax.swing.JLabel();
        precioAccesorio4 = new javax.swing.JLabel();
        stockCelulares2 = new javax.swing.JLabel();
        ProductoCelulares3 = new javax.swing.JPanel();
        imagenProductoCelularesProductDetailPanel3 = new javax.swing.JLabel();
        CategoriaAndModeloTituloMonitor3 = new javax.swing.JLabel();
        DescripcionCelulares3 = new javax.swing.JLabel();
        precioAccesorio5 = new javax.swing.JLabel();
        stockCelulares3 = new javax.swing.JLabel();
        ProductoCelulares4 = new javax.swing.JPanel();
        imagenProductoCelularesProductDetailPanel4 = new javax.swing.JLabel();
        CategoriaAndModeloTituloMonitor4 = new javax.swing.JLabel();
        DescripcionCelulares4 = new javax.swing.JLabel();
        precioAccesorio6 = new javax.swing.JLabel();
        stockCelulares4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1440, 1040));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        BotonInicio.setText("Inicio");
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        etiquetaProductosDisponibles.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        etiquetaProductosDisponibles.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaProductosDisponibles.setText("¡Productos disponibles!");

        ProductoCelulares1.setBackground(new java.awt.Color(219, 219, 219));
        ProductoCelulares1.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoCelularesProductDetailPanel1.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoCelularesProductDetailPanel1.setText("foto");

        CategoriaAndModeloTituloCelulares1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloCelulares1.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloCelulares1.setText("Iphone 10");

        DescripcionCelulares1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionCelulares1.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionCelulares1.setText("Celular Apple iPhone 16 128 GB 8 GB RAM Pantalla 6.1'' Cámara 48MP+12MP Rosado");
        DescripcionCelulares1.setToolTipText("");
        DescripcionCelulares1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioCelulares1.setForeground(new java.awt.Color(0, 0, 0));
        precioCelulares1.setText("Precio:  ₡430,000");

        stockCelulares1.setForeground(new java.awt.Color(0, 0, 0));
        stockCelulares1.setText("Cantidad: 6");

        javax.swing.GroupLayout ProductoCelulares1Layout = new javax.swing.GroupLayout(ProductoCelulares1);
        ProductoCelulares1.setLayout(ProductoCelulares1Layout);
        ProductoCelulares1Layout.setHorizontalGroup(
            ProductoCelulares1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoCelulares1Layout.createSequentialGroup()
                .addGroup(ProductoCelulares1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoCelulares1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoCelularesProductDetailPanel1))
                    .addGroup(ProductoCelulares1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(CategoriaAndModeloTituloCelulares1))
                    .addGroup(ProductoCelulares1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(DescripcionCelulares1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductoCelulares1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(ProductoCelulares1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockCelulares1)
                            .addComponent(precioCelulares1))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        ProductoCelulares1Layout.setVerticalGroup(
            ProductoCelulares1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoCelulares1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoCelularesProductDetailPanel1)
                .addGap(106, 106, 106)
                .addComponent(CategoriaAndModeloTituloCelulares1)
                .addGap(39, 39, 39)
                .addComponent(DescripcionCelulares1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precioCelulares1)
                .addGap(61, 61, 61)
                .addComponent(stockCelulares1)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        ProductoCelulares2.setBackground(new java.awt.Color(219, 219, 219));
        ProductoCelulares2.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoCelularesProductDetailPanel2.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoCelularesProductDetailPanel2.setText("foto");

        CategoriaAndModeloTituloMonitor2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloMonitor2.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloMonitor2.setText("Samsung Galaxy S24");

        DescripcionCelulares2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionCelulares2.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionCelulares2.setText("Celular Samsung Galaxy S24 Ultra 256GB 12GB-RAM");
        DescripcionCelulares2.setToolTipText("");
        DescripcionCelulares2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAccesorio4.setForeground(new java.awt.Color(0, 0, 0));
        precioAccesorio4.setText("Precio: ₡500,000");

        stockCelulares2.setForeground(new java.awt.Color(0, 0, 0));
        stockCelulares2.setText("Cantidad: 10");

        javax.swing.GroupLayout ProductoCelulares2Layout = new javax.swing.GroupLayout(ProductoCelulares2);
        ProductoCelulares2.setLayout(ProductoCelulares2Layout);
        ProductoCelulares2Layout.setHorizontalGroup(
            ProductoCelulares2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoCelulares2Layout.createSequentialGroup()
                .addGroup(ProductoCelulares2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoCelulares2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoCelularesProductDetailPanel2))
                    .addGroup(ProductoCelulares2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(DescripcionCelulares2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoCelulares2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(ProductoCelulares2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoCelulares2Layout.createSequentialGroup()
                        .addComponent(CategoriaAndModeloTituloMonitor2)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoCelulares2Layout.createSequentialGroup()
                        .addComponent(precioAccesorio4)
                        .addGap(122, 122, 122))))
            .addGroup(ProductoCelulares2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(stockCelulares2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ProductoCelulares2Layout.setVerticalGroup(
            ProductoCelulares2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoCelulares2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoCelularesProductDetailPanel2)
                .addGap(111, 111, 111)
                .addComponent(CategoriaAndModeloTituloMonitor2)
                .addGap(31, 31, 31)
                .addComponent(DescripcionCelulares2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precioAccesorio4)
                .addGap(55, 55, 55)
                .addComponent(stockCelulares2)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        ProductoCelulares3.setBackground(new java.awt.Color(219, 219, 219));
        ProductoCelulares3.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoCelularesProductDetailPanel3.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoCelularesProductDetailPanel3.setText("foto");

        CategoriaAndModeloTituloMonitor3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloMonitor3.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloMonitor3.setText("samsung galaxyflip");

        DescripcionCelulares3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionCelulares3.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionCelulares3.setText("Celular 5G Samsung Galaxy Z Flip6 Celeste 12GB RAM 256GB");
        DescripcionCelulares3.setToolTipText("");
        DescripcionCelulares3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAccesorio5.setForeground(new java.awt.Color(0, 0, 0));
        precioAccesorio5.setText("Precio: ₡212,990");

        stockCelulares3.setForeground(new java.awt.Color(0, 0, 0));
        stockCelulares3.setText("Cantidad: 8");

        javax.swing.GroupLayout ProductoCelulares3Layout = new javax.swing.GroupLayout(ProductoCelulares3);
        ProductoCelulares3.setLayout(ProductoCelulares3Layout);
        ProductoCelulares3Layout.setHorizontalGroup(
            ProductoCelulares3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoCelulares3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ProductoCelulares3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoCelulares3Layout.createSequentialGroup()
                        .addComponent(DescripcionCelulares3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoCelulares3Layout.createSequentialGroup()
                        .addComponent(precioAccesorio5)
                        .addGap(131, 131, 131))))
            .addGroup(ProductoCelulares3Layout.createSequentialGroup()
                .addGroup(ProductoCelulares3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoCelulares3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoCelularesProductDetailPanel3))
                    .addGroup(ProductoCelulares3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(CategoriaAndModeloTituloMonitor3))
                    .addGroup(ProductoCelulares3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(stockCelulares3)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        ProductoCelulares3Layout.setVerticalGroup(
            ProductoCelulares3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoCelulares3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoCelularesProductDetailPanel3)
                .addGap(120, 120, 120)
                .addComponent(CategoriaAndModeloTituloMonitor3)
                .addGap(36, 36, 36)
                .addComponent(DescripcionCelulares3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioAccesorio5)
                .addGap(42, 42, 42)
                .addComponent(stockCelulares3)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        ProductoCelulares4.setBackground(new java.awt.Color(219, 219, 219));
        ProductoCelulares4.setForeground(new java.awt.Color(237, 237, 237));

        imagenProductoCelularesProductDetailPanel4.setForeground(new java.awt.Color(0, 0, 0));
        imagenProductoCelularesProductDetailPanel4.setText("foto");

        CategoriaAndModeloTituloMonitor4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CategoriaAndModeloTituloMonitor4.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaAndModeloTituloMonitor4.setText("Huawei P70 Pro");

        DescripcionCelulares4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DescripcionCelulares4.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionCelulares4.setText("Huawei Telefono Celular P70 Pro 12Gb Ram 512Gb Rom Negro Hepburn");
        DescripcionCelulares4.setToolTipText("");
        DescripcionCelulares4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        precioAccesorio6.setForeground(new java.awt.Color(0, 0, 0));
        precioAccesorio6.setText("Precio: ₡196,990");

        stockCelulares4.setForeground(new java.awt.Color(0, 0, 0));
        stockCelulares4.setText("jLabel1");

        javax.swing.GroupLayout ProductoCelulares4Layout = new javax.swing.GroupLayout(ProductoCelulares4);
        ProductoCelulares4.setLayout(ProductoCelulares4Layout);
        ProductoCelulares4Layout.setHorizontalGroup(
            ProductoCelulares4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoCelulares4Layout.createSequentialGroup()
                .addGroup(ProductoCelulares4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoCelulares4Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(imagenProductoCelularesProductDetailPanel4))
                    .addGroup(ProductoCelulares4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(ProductoCelulares4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescripcionCelulares4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CategoriaAndModeloTituloMonitor4)))
                    .addGroup(ProductoCelulares4Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(stockCelulares4))
                    .addGroup(ProductoCelulares4Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(precioAccesorio6)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        ProductoCelulares4Layout.setVerticalGroup(
            ProductoCelulares4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoCelulares4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagenProductoCelularesProductDetailPanel4)
                .addGap(116, 116, 116)
                .addComponent(CategoriaAndModeloTituloMonitor4)
                .addGap(34, 34, 34)
                .addComponent(DescripcionCelulares4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(precioAccesorio6)
                .addGap(39, 39, 39)
                .addComponent(stockCelulares4)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(etiquetaProductosDisponibles))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(ProductoCelulares1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductoCelulares2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductoCelulares3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProductoCelulares4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaProductosDisponibles)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductoCelulares1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductoCelulares2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductoCelulares3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductoCelulares4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        if (parentFrame != null) {
            parentFrame.showCard(MainFrame.MENU_CLIENTE_CARD);
        } else {
            System.err.println("Error: No se ha establecido referencia al MainFrame");
        }
    }//GEN-LAST:event_BotonInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JLabel CategoriaAndModeloTituloCelulares1;
    private javax.swing.JLabel CategoriaAndModeloTituloMonitor2;
    private javax.swing.JLabel CategoriaAndModeloTituloMonitor3;
    private javax.swing.JLabel CategoriaAndModeloTituloMonitor4;
    private javax.swing.JLabel DescripcionCelulares1;
    private javax.swing.JLabel DescripcionCelulares2;
    private javax.swing.JLabel DescripcionCelulares3;
    private javax.swing.JLabel DescripcionCelulares4;
    private javax.swing.JPanel ProductoCelulares1;
    private javax.swing.JPanel ProductoCelulares2;
    private javax.swing.JPanel ProductoCelulares3;
    private javax.swing.JPanel ProductoCelulares4;
    private javax.swing.JLabel etiquetaProductosDisponibles;
    private javax.swing.JLabel imagenProductoCelularesProductDetailPanel1;
    private javax.swing.JLabel imagenProductoCelularesProductDetailPanel2;
    private javax.swing.JLabel imagenProductoCelularesProductDetailPanel3;
    private javax.swing.JLabel imagenProductoCelularesProductDetailPanel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel precioAccesorio4;
    private javax.swing.JLabel precioAccesorio5;
    private javax.swing.JLabel precioAccesorio6;
    private javax.swing.JLabel precioCelulares1;
    private javax.swing.JLabel stockCelulares1;
    private javax.swing.JLabel stockCelulares2;
    private javax.swing.JLabel stockCelulares3;
    private javax.swing.JLabel stockCelulares4;
    // End of variables declaration//GEN-END:variables
}
